#!/bin/sh

set -eu

connector_user=jobs_connector

if [ "${JOBS_CONNECTOR_DATABASE_USER:-$connector_user}" != "$connector_user" ]; then
  echo "JOBS_CONNECTOR_DATABASE_USER is immutable and must equal jobs_connector" >&2
  exit 1
fi

if [ "${POSTGRES_USER:-postgres}" = "$connector_user" ]; then
  echo "JOBS_CONNECTOR_DATABASE_USER must differ from POSTGRES_USER" >&2
  exit 1
fi

write_hba() {
  echo "# Generated by platform-infrastructure/postgres/config/start-postgres.sh"
  echo "# TYPE  DATABASE     USER                  ADDRESS  METHOD"
  printf 'local   jobs_db      "%s"                         scram-sha-256\n' "$connector_user"
  echo "local   replication  /^jobs_connector(_[a-z0-9_]+)?$             reject"
  echo "local   all          /^jobs_connector(_[a-z0-9_]+)?$             reject"
  printf 'host    jobs_db      "%s"                 all      scram-sha-256\n' "$connector_user"
  echo "host    replication  /^jobs_connector(_[a-z0-9_]+)?$     all      reject"
  echo "host    all          /^jobs_connector(_[a-z0-9_]+)?$     all      reject"
  echo "local   all          all                           trust"
  echo "local   replication  all                           trust"
  echo "host    all          all                   all      scram-sha-256"
  echo "host    replication  all                   all      scram-sha-256"
}

if [ "${1:-}" = "--print-hba" ]; then
  write_hba
  exit 0
fi

hba_path=/tmp/seo-platform-pg_hba.conf
write_hba > "$hba_path"
chmod 0644 "$hba_path"

exec /usr/local/bin/docker-entrypoint.sh "$@"
