#!/bin/sh

set -eu

connector_user=jobs_connector
service_roles='platform_owner platform_runtime seo_owner seo_runtime jobs_owner jobs_runtime realtime_owner realtime_runtime directus_runtime_owner'

if [ "${JOBS_CONNECTOR_DATABASE_USER:-$connector_user}" != "$connector_user" ]; then
  echo "JOBS_CONNECTOR_DATABASE_USER is immutable and must equal jobs_connector" >&2
  exit 1
fi

if [ "${POSTGRES_USER:-postgres}" = "$connector_user" ]; then
  echo "JOBS_CONNECTOR_DATABASE_USER must differ from POSTGRES_USER" >&2
  exit 1
fi

for service_role in $service_roles; do
  if [ "${POSTGRES_USER:-postgres}" = "$service_role" ]; then
    echo "POSTGRES_USER must differ from canonical service database roles" >&2
    exit 1
  fi
done

write_hba() {
  echo "# Generated by platform-infrastructure/postgres/config/start-postgres.sh"
  echo "# TYPE  DATABASE     USER                  ADDRESS  METHOD"
  echo 'local   platform_db  "platform_owner"                    scram-sha-256'
  echo 'local   platform_db  "platform_runtime"                  scram-sha-256'
  echo 'local   seo_db       "seo_owner"                         scram-sha-256'
  echo 'local   seo_db       "seo_runtime"                       scram-sha-256'
  echo 'local   jobs_db      "jobs_owner"                        scram-sha-256'
  echo 'local   jobs_db      "jobs_runtime"                      scram-sha-256'
  echo 'local   realtime_db  "realtime_owner"                    scram-sha-256'
  echo 'local   realtime_db  "realtime_runtime"                  scram-sha-256'
  echo 'local   directus_db  "directus_runtime_owner"            scram-sha-256'
  printf 'local   jobs_db      "%s"                         scram-sha-256\n' "$connector_user"
  echo 'local   replication  /^(platform|seo|jobs|realtime)_(owner|runtime)(_[a-z0-9_]+)?$  reject'
  echo 'local   all          /^(platform|seo|jobs|realtime)_(owner|runtime)(_[a-z0-9_]+)?$  reject'
  echo 'local   replication  /^directus_runtime_owner(_[a-z0-9_]+)?$          reject'
  echo 'local   all          /^directus_runtime_owner(_[a-z0-9_]+)?$          reject'
  echo "local   replication  /^jobs_connector(_[a-z0-9_]+)?$             reject"
  echo "local   all          /^jobs_connector(_[a-z0-9_]+)?$             reject"
  echo 'host    platform_db  "platform_owner"                    all      scram-sha-256'
  echo 'host    platform_db  "platform_runtime"                  all      scram-sha-256'
  echo 'host    seo_db       "seo_owner"                         all      scram-sha-256'
  echo 'host    seo_db       "seo_runtime"                       all      scram-sha-256'
  echo 'host    jobs_db      "jobs_owner"                        all      scram-sha-256'
  echo 'host    jobs_db      "jobs_runtime"                      all      scram-sha-256'
  echo 'host    realtime_db  "realtime_owner"                    all      scram-sha-256'
  echo 'host    realtime_db  "realtime_runtime"                  all      scram-sha-256'
  echo 'host    directus_db  "directus_runtime_owner"            all      scram-sha-256'
  printf 'host    jobs_db      "%s"                 all      scram-sha-256\n' "$connector_user"
  echo 'host    replication  /^(platform|seo|jobs|realtime)_(owner|runtime)(_[a-z0-9_]+)?$  all      reject'
  echo 'host    all          /^(platform|seo|jobs|realtime)_(owner|runtime)(_[a-z0-9_]+)?$  all      reject'
  echo 'host    replication  /^directus_runtime_owner(_[a-z0-9_]+)?$          all      reject'
  echo 'host    all          /^directus_runtime_owner(_[a-z0-9_]+)?$          all      reject'
  echo "host    replication  /^jobs_connector(_[a-z0-9_]+)?$     all      reject"
  echo "host    all          /^jobs_connector(_[a-z0-9_]+)?$     all      reject"
  echo "local   all          all                           trust"
  echo "local   replication  all                           trust"
  echo "host    all          all                   all      scram-sha-256"
  echo "host    replication  all                   all      scram-sha-256"
}

if [ "${1:-}" = "--print-hba" ]; then
  write_hba
  exit 0
fi

hba_path=/tmp/seo-platform-pg_hba.conf
write_hba > "$hba_path"
chmod 0644 "$hba_path"

exec /usr/local/bin/docker-entrypoint.sh "$@"
