import { assertSidebarBoundary } from "./workspace-sidebar-geometry.mjs";
import { chooseDateInput, chooseTimeInput } from "./custom-date-controls.mjs";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import test from "node:test";
import { setTimeout as delay } from "node:timers/promises";
import { chromium, request } from "playwright";
import { crawlSiteFixture } from "./crawl-site-fixture.mjs";
import { remoteWorkerFixture } from "./remote-worker-fixture.mjs";
import { delimitedFile } from "./position-import-files.mjs";

test("HTTPS UI → remote worker → real public site → saved page facts/positions → UI", { skip: process.env.SEO_PLATFORM_E2E_CONFIRM !== "CREATE_TEST_DATA", timeout: 600_000 }, async (t) => {
  const base = process.env.SEO_PLATFORM_PUBLIC_URL, output = process.env.SEO_PLATFORM_E2E_OUTPUT_DIR;
  assert.equal(base, "https://144.31.221.28:3000");
  const site = await crawlSiteFixture(t), worker = await remoteWorkerFixture(t);
  const fixtures = JSON.parse(await readFile(process.env.SEO_PLATFORM_SESSION_FIXTURES, "utf8"));
  const [user, , , foreign] = fixtures, staff = fixtures.find(fixture => fixture.role === "SUPER_ADMIN");
  assert.ok(staff);
  const api = await request.newContext({ baseURL: base, storageState: user.storageState }), outsider = await request.newContext({ baseURL: base, storageState: foreign.storageState });
  const adminApi = await request.newContext({ baseURL: base, storageState: staff.storageState });
  const browser = await chromium.launch({ headless: true });
  t.after(async () => { await browser.close(); await api.dispose(); await outsider.dispose(); await adminApi.dispose(); });
  async function call(method, path, data, version) {
    const csrf = (await api.storageState()).cookies.find((cookie) => cookie.name === "seo_csrf")?.value;
    const response = await api.fetch("/app/api/" + path, { method, headers: { Origin: base, ...(csrf ? { "X-CSRF-Token": csrf } : {}), ...(method === "GET" ? {} : { "Idempotency-Key": randomUUID() }), ...(version === undefined ? {} : { "If-Match": `"v${version}"` }) }, ...(data === undefined ? {} : { data }) });
    const body = await response.json(); assert.ok(response.ok(), `${method} ${path}: ${response.status()} ${body.error?.code ?? ""}`); return body.data;
  }
  const workspace = await call("POST", "workspaces", { name: "Проверка обхода и карты", country: "RU", locale: "ru", timezone: "Europe/Moscow", billingCurrency: "RUB" });
  const project = await call("POST", `workspaces/${workspace.id}/projects`, { name: "Реальный контрольный сайт", domain: site.domain, locale: "ru", timezone: "Europe/Moscow" });
  const context = await browser.newContext({ storageState: await api.storageState(), viewport: { width: 1600, height: 1000 }, timezoneId: "Europe/Moscow" });
  await context.addCookies([{ name: "seo_workspace", value: workspace.id, url: base }, { name: "seo_project", value: project.id, url: base }]);
  const page = await context.newPage(), errors = [], serverErrors = [], requests = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("request", (req) => { if (new URL(req.url()).pathname.includes("/pages/")) requests.push(new URL(req.url()).pathname); });
  page.on("response", (response) => { if (response.status() >= 500 && new URL(response.url()).pathname.startsWith("/app/api/")) serverErrors.push({ path: new URL(response.url()).pathname, status: response.status() }); });

  await t.test("real CSV import provides independently measured average positions", async () => {
    const bytes = delimitedFile([["Запрос", "Целевой URL", "08.10.2026", "URL · 08.10.2026"], ["Страница ключ A", site.root + "services/", 4, site.root + "services/"], ["Страница ключ B", site.root + "services/", 9, site.root + "services/"], ["Страница другой URL", site.root + "services/", 20, site.root + "other/"], ["Страница не найдена", site.root + "services/", "--", ""], ["Страница без замера", site.root + "services/", "", ""]]);
    await page.goto(base + "/app/semantics"); await page.getByRole("button", { name: "Импорт", exact: true }).click();
    const upload = page.locator(".semantic-upload");
    await upload.locator(".semantic-import-source-option").filter({ has: page.locator("strong", { hasText: /^Позиции$/u }) }).click();
    await upload.locator('input[type="file"]').setInputFiles({ name: "page-positions.csv", mimeType: "text/csv", buffer: bytes });
    const created = page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname.endsWith(`/projects/${project.id}/imports`));
    await upload.getByRole("button", { name: "Начать загрузку", exact: true }).click();
    const response = await created; assert.equal(response.status(), 201);
    const imported = (await response.json()).data;
    await upload.locator(".import-spreadsheet").waitFor({ timeout: 120_000 });
    await upload.getByRole("checkbox", { name: "Добавлять отсутствующие запросы", exact: false }).check();
    await upload.getByRole("button", { name: "Проверить импорт", exact: true }).click();
    await upload.locator('[aria-label="Проверка импорта"]').waitFor({ timeout: 120_000 });
    await upload.getByRole("button", { name: /^Импортировать\s+5$/u }).click();
    await upload.locator('[aria-label="Результат импорта"]').waitFor({ timeout: 120_000 });
    assert.equal((await call("GET", `projects/${project.id}/imports/${imported.id}`)).status, "COMPLETED");
    const adminResponse = await adminApi.get(`/admin/api/operations/${imported.id}`); assert.equal(adminResponse.status(), 200);
    const operation = (await adminResponse.json()).data; assert.equal(operation.type, "SEMANTIC_IMPORT"); assert.equal(operation.status, "COMPLETED");
    const adminPage = await browser.newPage({ storageState: staff.storageState, viewport: { width: 1600, height: 1000 } });
    await adminPage.goto(`${base}/admin?screen=operations&type=SEMANTIC_IMPORT&operation=${imported.id}`);
    await adminPage.locator(".operation-drawer").getByText("Импорт семантики", { exact: true }).waitFor();
    await adminPage.screenshot({ path: output + "/admin-import-operation.png", animations: "disabled" });
    const pendingImport = await call("POST", `projects/${project.id}/imports`, response.request().postDataJSON());
    const listed = adminPage.waitForResponse(response => response.request().method() === "GET" && new URL(response.url()).pathname === "/admin/api/operations");
    await adminPage.goto(`${base}/admin?screen=operations&type=SEMANTIC_IMPORT`);
    assert.equal((await (await listed).json()).data.data[0].id, pendingImport.id);
    await adminPage.locator(".operation-row:not(.operation-head)").first().getByRole("button", { name: "Остановить", exact: true }).click();
    const confirmation = adminPage.locator("dialog.admin-action-dialog");
    await confirmation.getByRole("checkbox", { name: "Подтверждаю действие", exact: true }).check();
    const cancelledRequest = adminPage.waitForResponse(response => response.request().method() === "POST" && new URL(response.url()).pathname.endsWith(`/operations/${pendingImport.id}/cancel`));
    await confirmation.getByRole("button", { name: "Подтвердить", exact: true }).click();
    const cancelled = await cancelledRequest;
    assert.equal(cancelled.status(), 201); assert.equal((await cancelled.json()).data.status, "CANCELLED");
    assert.equal((await call("GET", `projects/${project.id}/imports/${pendingImport.id}`)).status, "CANCELLED");
    await adminPage.close();
    assert.equal((await outsider.get("/admin/api/operations")).status(), 403);

    const pages = await call("GET", `projects/${project.id}/pages?limit=100`), service = pages.pages.find((entry) => entry.normalizedUrl === site.root + "services/"); assert.ok(service);
    const stats = await call("GET", `projects/${project.id}/pages/rank-statistics?${new URLSearchParams({ pageIds: service.id, dimensionKey: "YANDEX|RU|213|ru|DESKTOP", date: "latest" })}`);
    assert.equal(stats.pages[0].averagePosition, 6.5); assert.equal(stats.pages[0].measuredCount, 4); assert.equal(stats.pages[0].differentPageCount, 1);
  });

  await t.test("semantic export runs on the remote worker and appears in the admin journal", async () => {
    await page.goto(base + "/app/semantics"); await page.getByRole("button", { name: "Экспорт", exact: true }).click();
    const modal = page.getByRole("dialog", { name: "Экспорт семантики", exact: true });
    const created = page.waitForResponse(response => response.request().method() === "POST" && new URL(response.url()).pathname.endsWith(`/projects/${project.id}/exports`));
    await modal.getByRole("button", { name: "Экспортировать", exact: true }).click();
    const response = await created; assert.equal(response.status(), 202); let exported = (await response.json()).data;
    for (let attempt = 0; attempt < 60; attempt++) { exported = await call("GET", `projects/${project.id}/exports/${exported.id}`); if (!["QUEUED", "RUNNING"].includes(exported.status)) break; await delay(1000); }
    assert.equal(exported.status, "COMPLETED"); assert.equal(exported.rowCount, 5);
    assert.ok(await worker.prisma.remoteWorkTask.count({ where: { operationId: exported.id, nodeId: worker.nodeId, capability: "EXPORT", state: "COMPLETED" } }));
    const operationResponse = await adminApi.get(`/admin/api/operations/${exported.id}`); assert.equal(operationResponse.status(), 200);
    const operation = (await operationResponse.json()).data; assert.equal(operation.type, "SEMANTIC_EXPORT"); assert.equal(operation.status, "COMPLETED");
  });

  let crawl, crawlInput;
  await t.test("UI config passes controls through the center to the remote crawl worker", async () => {
    await page.goto(`${base}/app/projects/${project.id}/tools/http-status-checker`);
    await page.getByRole("combobox", { name: "Источник URL", exact: true }).click(); await page.getByRole("option", { name: "Список URL", exact: true }).click();
    await page.getByLabel("URL — по одному в строке", { exact: false }).fill(site.root);
    await page.getByLabel("Лимит страниц", { exact: true }).fill("20");
    await page.getByRole("checkbox", { name: "Находить страницы по внутренним ссылкам", exact: true }).check();
    await page.getByRole("checkbox", { name: "Использовать sitemap", exact: true }).check();
    await page.getByLabel("Sitemap URL — до 10", { exact: false }).fill(site.root + "sitemap.xml");
    await page.locator("details").filter({ has: page.locator("summary", { hasText: "Глубина, пути и параметры URL" }) }).locator("summary").click();
    await page.getByRole("checkbox", { name: "Не переходить по ссылкам со страниц с nofollow", exact: true }).check();
    await page.getByRole("combobox", { name: "Скорость на домен", exact: true }).click(); await page.getByRole("option", { name: "4 страницы/с", exact: true }).click();
    const created = page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === `/app/api/projects/${project.id}/crawls`);
    await page.getByRole("button", { name: "Запустить обход", exact: true }).click();
    const response = await created; crawlInput = response.request().postDataJSON(); crawl = (await response.json()).data; assert.equal(response.status(), 202);
    assert.equal(crawlInput.maxUrls, 20); assert.equal(crawlInput.requestsPerMinute, 240);
    assert.equal(crawl.config.requestsPerMinute, 240); assert.equal(crawl.config.respectNofollow, true); assert.equal(crawl.config.requestTimeoutMs, 20_000); assert.equal(crawl.config.snapshotIdentity, "REQUESTED_URL");
    let remoteInAdmin = false;
    for (let attempt = 0; attempt < 80; attempt++) {
      crawl = await call("GET", `projects/${project.id}/crawls/${crawl.id}`);
      const operationResponse = await adminApi.get(`/admin/api/operations/${crawl.jobId}`); assert.equal(operationResponse.status(), 200);
      const operation = (await operationResponse.json()).data; assert.equal(operation.type, "TECHNICAL_CRAWL");
      if (operation.workers?.some(node => node.nodeId === worker.nodeId)) remoteInAdmin = true;
      if (!["QUEUED", "RUNNING", "CANCEL_REQUESTED"].includes(crawl.status)) break; await delay(1_000);
    }
    assert.equal(remoteInAdmin, true, "The actual remote crawl worker appears in the admin operation");
    assert.equal(crawl.status, "COMPLETED"); assert.ok(crawl.processedUrls >= 8); assert.equal(crawl.blockedUrls, 1); assert.equal(crawl.processedUrls, crawl.successfulUrls + crawl.failedUrls + crawl.blockedUrls);
    assert.equal(site.events.filter((event) => event.path === "/blocked/").length, 0, "robots never bypassed");
    assert.equal(site.events.filter((event) => event.path === "/never-discovered/").length, 0, "nofollow control affects discovery");
    const work = await worker.prisma.remoteWorkTask.count({ where: { operationId: crawl.id, nodeId: worker.nodeId, state: "COMPLETED" } }); assert.ok(work >= 8, "actual remote work receipts, not local-only execution");
    await page.getByRole("heading", { name: "Обход завершён", exact: true }).waitFor({ timeout: 15_000 });
    await page.screenshot({ path: output + "/crawl-completed.png" });
  });

  assert.equal(crawl?.status, "COMPLETED", "Do not continue with page assertions after a failed crawl phase");
  await t.test("page map, scoped robot facts, semantic links, local widths and full-height note", async () => {
    const collection = await call("GET", `projects/${project.id}/pages?limit=100`);
    const service = collection.pages.find((entry) => entry.normalizedUrl === site.root + "services/"), blocked = collection.pages.find((entry) => entry.normalizedUrl === site.root + "blocked/"), agent = collection.pages.find((entry) => entry.normalizedUrl === site.root + "agent-meta/"), old = collection.pages.find((entry) => entry.normalizedUrl === site.root + "services/old/");
    assert.ok(service && blocked && agent && old);
    assert.equal((await call("GET", `projects/${project.id}/pages/${blocked.id}`)).latestCrawl.statusCode, 0);
    assert.equal((await call("GET", `projects/${project.id}/pages/${old.id}`)).latestCrawl.finalUrl, site.root + "services/new/");
    assert.equal(old.indexability, "REDIRECTED");
    const detail = await call("GET", `projects/${project.id}/pages/${agent.id}`);
    assert.ok(detail.latestCrawl.metaTags.some((tag) => tag.name === "googlebot" && tag.content === "noindex"));
    assert.ok(detail.latestCrawl.metaTags.some((tag) => tag.name === "yandex" && tag.content === "index, follow"));
    assert.ok([403,404].includes((await outsider.get(`/app/api/projects/${project.id}/pages/${service.id}/panel?section=SEMANTICS&limit=50`)).status()));
    await page.goto(`${base}/app/projects/${project.id}/pages?pageId=${service.id}`);
    const inspector = page.getByRole("complementary", { name: "Информация о странице", exact: true }); await inspector.waitFor();
    const beforeRecheck = site.events.length;
    const started = page.waitForResponse(response => response.request().method() === "POST" && new URL(response.url()).pathname.endsWith(`/projects/${project.id}/crawls`));
    await inspector.getByRole("button", { name: "Перепроверить", exact: true }).click();
    const startedResponse = await started; const startedBody = await startedResponse.json(); assert.equal(startedResponse.status(), 202, JSON.stringify({ error: startedBody.error, fields: Object.keys(startedResponse.request().postDataJSON()) })); let repeat = startedBody.data;
    assert.deepEqual(repeat.config.startUrls, [service.normalizedUrl]); assert.equal(repeat.config.maxUrls, 1); assert.equal(repeat.config.maxDepth, 0); assert.equal(startedResponse.request().postDataJSON().maxDepth, 0); assert.deepEqual(repeat.config.sitemapUrls, []);
    for (let attempt = 0; attempt < 80; attempt++) { repeat = await call("GET", `projects/${project.id}/crawls/${repeat.id}`); if (!["QUEUED", "RUNNING"].includes(repeat.status)) break; await delay(1000); }
    assert.equal(repeat.status, "COMPLETED"); assert.equal(repeat.processedUrls, 1);
    assert.deepEqual([...new Set(site.events.slice(beforeRecheck).filter(event => event.path !== "/robots.txt").map(event => event.path))], ["/services/"]);
    await inspector.getByRole("button", { name: "Перепроверить", exact: true }).waitFor();
    await page.locator(`tr[data-page-id="${service.id}"] .page-map-average`).filter({ hasText: "6,5" }).waitFor({ timeout: 30_000 });
    await inspector.getByRole("tab", { name: "Семантика", exact: true }).click(); await inspector.getByRole("link", { name: "Страница ключ A", exact: true }).waitFor();
    await assertSidebarBoundary(page.locator('[data-workspace-sidebar="left"]'));
    await assertSidebarBoundary(page.locator('[data-workspace-sidebar="right"]'), "right");
    const alignments = await page.locator('tr[data-page-id] td[data-column]:not([data-column="url"])').evaluateAll(nodes => nodes.map(node => getComputedStyle(node).textAlign));
    assert.ok(alignments.length && alignments.every(value => value === "center"));
    const noindex = page.locator('tr[data-page-id] .page-index-noindex').first();
    const badge = await noindex.evaluate(node => ({ display: getComputedStyle(node).display, radius: getComputedStyle(node).borderRadius, height: node.getBoundingClientRect().height }));
    assert.equal(badge.display, "inline-flex"); assert.ok(parseFloat(badge.radius) >= 10 && badge.height >= 20);
    await page.screenshot({ path: output + "/page-map-table.png" });
    const contentGeometry = await page.locator(".page-map-table-wrap").boundingBox();
    assert.ok(contentGeometry.y < 200, "controls leave the main area for page data");
    assert.ok(contentGeometry.height > 700, "table fills the remaining desktop height");
    await inspector.getByRole("tab", { name: "История", exact: true }).click();
    const firstSnapshot = inspector.getByRole("combobox", { name: "Первый снимок", exact: true });
    await firstSnapshot.click();
    const snapshots = page.getByRole("listbox", { name: "Первый снимок", exact: true });
    assert.ok(await snapshots.getByRole("option").count() >= 2);
    await page.screenshot({ path: output + "/page-history-select.png" });
    await snapshots.getByRole("option").last().click();
    assert.equal(await inspector.locator("select").count(), 0);
    await firstSnapshot.focus(); await page.keyboard.press("ArrowDown"); await page.keyboard.press("Escape");
    assert.equal(await firstSnapshot.getAttribute("aria-expanded"), "false");
    await page.screenshot({ path: output + "/page-history.png" });
    await page.getByRole("combobox", { name: "Поисковый срез для позиций", exact: true }).click();
    await page.getByRole("listbox", { name: "Поисковый срез для позиций", exact: true }).waitFor();
    assert.ok(await page.getByRole("listbox", { name: "Поисковый срез для позиций", exact: true }).locator('.search-engine-logo').count() > 0);
    assert.ok(await page.getByRole("listbox", { name: "Поисковый срез для позиций", exact: true }).locator('.semantic-rank-device-badge svg').count() > 0);
    await page.screenshot({ path: output + "/page-rank-dimension-select.png" }); await page.keyboard.press("Escape");
    await chooseDateInput(page, page.getByRole("combobox", { name: "Дата съёма для карты страниц", exact: true }), "2026-10-08");
    await page.getByRole("button", { name: "Средняя позиция", exact: true }).click();
    await page.locator('th[aria-sort="ascending"]').filter({ has: page.getByRole("button", { name: "Средняя позиция", exact: true }) }).waitFor();
    await page.waitForFunction(id => document.querySelector("tr[data-page-id]")?.getAttribute("data-page-id") === id, service.id);
    const preferenceKey = `seo-platform:page-map-layout:v2:${user.userId}:${project.id}`;
    await page.waitForFunction(key => JSON.parse(localStorage.getItem(key) ?? "{}").sortField === "AVERAGE_POSITION", preferenceKey);
    await page.evaluate(({ key, other }) => localStorage.setItem(other, JSON.stringify({ ...JSON.parse(localStorage.getItem(key)), sortField: "HTTP", sortDirection: "DESC", rankDate: "2025-01-01" })), { key: preferenceKey, other: `seo-platform:page-map-layout:v2:${foreign.userId}:${project.id}` });
    await page.reload(); await page.locator('th[aria-sort="ascending"]').filter({ has: page.getByRole("button", { name: "Средняя позиция", exact: true }) }).waitFor();
    assert.equal((await page.evaluate(key => JSON.parse(localStorage.getItem(key)), preferenceKey)).rankDate, "2026-10-08");
    await page.getByRole("button", { name: "HTTP", exact: true }).click();
    const headerHttp = page.locator('th[aria-sort="ascending"]').filter({ has: page.getByRole("button", { name: "HTTP", exact: true }) }); await headerHttp.waitFor();
    await page.getByRole("button", { name: "HTTP", exact: true }).click(); await page.locator('th[aria-sort="descending"]').filter({ has: page.getByRole("button", { name: "HTTP", exact: true }) }).waitFor();
    await page.getByRole("button", { name: "URL / страница", exact: true }).click();
    const folderButton = page.getByRole("button", { name: /^\/services\s+3$/u });
    const folderStarted = performance.now(); await folderButton.click(); await page.waitForFunction(id => document.querySelector("tr[data-page-id]")?.getAttribute("data-page-id") === id, service.id);
    const folderElapsed = performance.now() - folderStarted;
    await page.getByRole("button", { name: /^Все страницы/u }).click(); await folderButton.click();
    assert.ok(performance.now() - folderStarted < 2500, "folder navigation and repeat stay responsive");
    await page.locator(`tr[data-page-id="${service.id}"]`).click();
    await inspector.waitFor();
    await page.screenshot({ path: output + "/page-map-sorted-folder.png", animations: "disabled" });
    console.log(JSON.stringify({ folderElapsedMs: Math.round(folderElapsed) }));
    await inspector.getByRole("button", { name: "Изменить", exact: true }).click();
    const editor = page.getByRole("dialog", { name: "Параметры страницы", exact: true });
    await page.screenshot({ path: output + "/page-editor-basic.png" });
    await editor.getByRole("textbox", { name: "Заметки", exact: true }).fill("Проверено через редактор страницы");
    await editor.locator("summary").filter({ hasText: "Дополнительные параметры" }).click();
    await chooseDateInput(page, editor.getByRole("combobox", { name: "Опубликована", exact: true }), "2026-10-08T09:15");
    await editor.getByRole("combobox", { name: "Ответственный", exact: true }).click();
    await page.getByRole("option", { name: "Analytics fixture USER", exact: true }).click();
    assert.equal(await editor.locator('select,input[type="date"],input[type="datetime-local"]').count(), 0);
    const editorBoxes = await editor.evaluate((node) => { const header = node.querySelector('header').getBoundingClientRect(), body = node.querySelector('.semantic-modal-body').getBoundingClientRect(), footer = node.querySelector('footer').getBoundingClientRect(); return { headerBottom: header.bottom, bodyTop: body.top, bodyBottom: body.bottom, footerTop: footer.top }; });
    assert.ok(editorBoxes.headerBottom <= editorBoxes.bodyTop + 1 && editorBoxes.bodyBottom <= editorBoxes.footerTop + 1, "modal header and footer never cover the scrolling fields");
    await page.screenshot({ path: output + "/page-editor.png" });
    const saved = page.waitForResponse((response) => response.request().method() === "PATCH" && new URL(response.url()).pathname.endsWith(`/pages/${service.id}`));
    await editor.getByRole("button", { name: "Сохранить", exact: true }).click(); assert.equal((await saved).status(), 200);
    const updated = await call("GET", `projects/${project.id}/pages/${service.id}`);
    assert.equal(updated.notes, "Проверено через редактор страницы"); assert.equal(updated.publishedAt, "2026-10-08T06:15:00.000Z"); assert.equal(updated.ownerId, user.userId);

    await inspector.getByRole("tab", { name: "Семантика", exact: true }).click();

    const resize = page.getByRole("separator", { name: /Изменить ширину.*Средняя позиция/u }); await resize.focus(); const before = Number(await resize.getAttribute("aria-valuenow")); await page.keyboard.press("ArrowRight"); assert.equal(Number(await resize.getAttribute("aria-valuenow")), before + 12);
    await page.reload(); await page.getByRole("separator", { name: /Изменить ширину.*Средняя позиция/u }).waitFor(); assert.equal(Number(await page.getByRole("separator", { name: /Изменить ширину.*Средняя позиция/u }).getAttribute("aria-valuenow")), before + 12);
    await page.getByRole("button", { name: "Схема", exact: true }).click(); await page.getByLabel("Карта страниц — схема", { exact: true }).waitFor(); await page.screenshot({ path: output + "/page-map-diagram.png" });
    const viewport = page.getByLabel("Карта страниц — схема", { exact: true });
    assert.equal(await viewport.getByRole("button", { name: "Ещё", exact: true }).count(), 0);
    assert.equal(await viewport.getByRole("button", { name: "Страница", exact: true }).count(), 0);
    assert.equal(await viewport.getByRole("button", { name: "Раздел", exact: true }).count(), 0);
    const canvas = viewport.locator("[data-canvas-transform]");
    const originalTransform = await canvas.evaluate((node) => getComputedStyle(node).transform);
    const box = await viewport.boundingBox();
    await page.mouse.move(box.x + box.width - 20, box.y + box.height - 60);
    await page.mouse.down(); await page.mouse.move(box.x + box.width - 160, box.y + box.height - 150, { steps: 6 }); await page.mouse.up();
    assert.notEqual(await canvas.evaluate((node) => getComputedStyle(node).transform), originalTransform, "drag pans the canvas");
    await page.getByRole("button", { name: "Вписать", exact: true }).click();
    const fitted = await canvas.boundingBox();
    assert.ok(fitted.x >= box.x && fitted.y >= box.y && fitted.x + fitted.width <= box.x + box.width + 1 && fitted.y + fitted.height <= box.y + box.height + 1, "fit contains the whole diagram");
    await page.screenshot({ path: output + "/page-map-diagram-fit.png" });
    const beforeKeyboard = await canvas.evaluate((node) => getComputedStyle(node).transform);
    await viewport.focus(); await page.keyboard.press("ArrowRight");
    assert.notEqual(await canvas.evaluate((node) => getComputedStyle(node).transform), beforeKeyboard, "canvas can be panned with the keyboard");
    await page.waitForFunction(() => !document.querySelector(".page-map-refresh")?.disabled);
    const count = requests.length; await page.getByRole("button", { name: "Увеличить масштаб", exact: true }).click(); await delay(200); assert.equal(requests.length, count, "zoom is local, no database reads");
    for (let start = 0; start < 55; start += 5) await Promise.all(Array.from({ length: Math.min(5, 55 - start) }, (_, offset) => call("POST", `projects/${project.id}/pages`, { url: `${site.root}services/generated-${start + offset}/`, aliases: [], pageType: "EXISTING", indexability: "UNKNOWN", priority: 0 })));
    // Section selection crosses browser → BFF → public API → owning service.
    await page.getByRole("button", { name: "Список", exact: true }).click();
    const filteredResponse = page.waitForResponse((response) => new URL(response.url()).pathname.endsWith(`/projects/${project.id}/pages`) && new URL(response.url()).searchParams.has("pathPrefix") && response.status() === 200);
    await page.getByRole("button", { name: "Обновить карту страниц", exact: true }).click();
    await filteredResponse;
    await page.waitForFunction(() => { const rows = [...document.querySelectorAll("tr[data-page-id] .page-map-url a")]; return rows.length > 0 && rows.every((row) => row.textContent.startsWith("/services")); });
    const paths = await page.locator("tr[data-page-id] .page-map-url a").allTextContents();
    await page.waitForFunction(() => document.querySelector("tr[data-page-id] .page-map-url a")?.textContent === "/services/");
    assert.equal((await page.locator("tr[data-page-id] .page-map-url a").allTextContents())[0], "/services/");
    assert.equal(await page.locator(".page-map-tree ul").count(), 0, "the sidebar lists sections without page leaves");
    assert.ok(paths.length > 0 && paths.every((value) => value.startsWith("/services")));
    await page.getByRole("button", { name: "Схема", exact: true }).click();
    await page.getByRole("button", { name: "Вписать", exact: true }).click();
    const olderPage = viewport.getByRole("button", { name: "/services/generated-0/", exact: true });
    await olderPage.click();
    await inspector.getByRole("heading", { name: "/services/generated-0/", exact: true }).waitFor();
    assert.equal(await page.getByRole("button", { name: "Загрузить ещё страницы выборки", exact: true }).count(), 0, "section diagram includes URLs beyond the first API page");
    await page.screenshot({ path: output + "/large-section-diagram.png" });
    await inspector.getByRole("button", { name: "Закрыть страницу", exact: true }).click();
    await page.getByRole("button", { name: "Список", exact: true }).click();

    const allResponse = page.waitForResponse((response) => new URL(response.url()).pathname.endsWith(`/projects/${project.id}/pages`) && !new URL(response.url()).searchParams.has("pathPrefix") && response.status() === 200);
    await page.locator(".page-map-tree-root").click(); await allResponse;
    await page.goto(`${base}/app/projects/${project.id}/pages?pageId=${service.id}`);
    await inspector.waitFor();
    await page.getByRole("button", { name: "Схема", exact: true }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, "mobile has no horizontal page overflow");
    await page.screenshot({ path: output + "/page-map-mobile.png" });
    await inspector.getByRole("button", { name: "Закрыть страницу", exact: true }).click();
    await page.getByRole("button", { name: "Вписать", exact: true }).click();
    const mobileCanvas = await viewport.boundingBox();
    assert.ok(mobileCanvas.height > 350, "mobile controls leave space for the canvas");
    await page.screenshot({ path: output + "/page-map-mobile-canvas.png" });
    await page.setViewportSize({ width: 1600, height: 1000 });
    await page.goto(base + "/app/semantics");
    await page.getByRole("button", { name: "Колонки и представления", exact: true }).click();
    const layout = page.getByRole("complementary", { name: "Колонки и представления", exact: true });
    await layout.getByRole("button", { name: "Работа с URL", exact: true }).click();
    await layout.getByRole("button", { name: "Применить", exact: true }).click();
    const targetHeader = page.getByRole("button", { name: /^Целевой URL[.]/u }); await targetHeader.waitFor();
    const targetColumn = await targetHeader.evaluate(node => node.closest("th").cellIndex);
    const keywordRow = page.locator("tr").filter({ hasText: "Страница ключ A" }).first();
    const targetLink = keywordRow.locator("td").nth(targetColumn).getByRole("link");
    assert.equal(await targetLink.getAttribute("href"), service.normalizedUrl); assert.equal(await targetLink.getAttribute("target"), "_blank");
    assert.ok((await targetLink.getAttribute("class")).includes("semantic-ranking-url-link"));
    await keywordRow.locator(".semantic-query-text").click();
    const keyword = page.locator(".semantic-keyword-inspector"); await keyword.waitFor();
    const tabGeometry = await keyword.locator(".semantic-inspector-icon-tab").evaluateAll(nodes => nodes.map(node => ({ width: node.getBoundingClientRect().width, icon: node.querySelector("svg").getBoundingClientRect().width })));
    assert.equal(tabGeometry.length, 2); assert.deepEqual(tabGeometry[0], tabGeometry[1]); assert.equal(tabGeometry[0].icon, 15); await keyword.getByRole("tab", { name: "Страница", exact: true }).click(); await keyword.getByRole("tab", { name: "Страница", exact: true, selected: true }).waitFor(); await keyword.locator(".semantic-inspector-page-tab").waitFor(); await keyword.getByText("Последняя проверка", { exact: true }).waitFor();
    await page.screenshot({ path: output + "/keyword-page.png" });
    await keyword.getByRole("tab", { name: "Заметка", exact: true }).click(); const textarea = keyword.getByRole("textbox", { name: "Заметка к запросу", exact: true }); await textarea.fill("Контрольная заметка страницы");
    const geometry = await textarea.evaluate((node) => ({ resize: getComputedStyle(node).resize, height: node.getBoundingClientRect().height })); assert.equal(geometry.resize, "none"); assert.ok(geometry.height > 350);
    await keyword.getByRole("button", { name: "Сохранить", exact: true }).click(); await page.screenshot({ path: output + "/keyword-note.png" });
    await page.goto(base + "/app/settings/notifications");
    const digest = page.getByRole("combobox", { name: "Время дневного дайджеста", exact: true });
    await chooseTimeInput(page, digest, "09:15");
    await page.screenshot({ path: output + "/custom-time-input.png" });
    const preferencesSaved = page.waitForResponse((response) => response.request().method() === "PATCH" && new URL(response.url()).pathname.endsWith("/me/notification-preferences"));
    await page.getByRole("button", { name: "Сохранить", exact: true }).click(); assert.equal((await preferencesSaved).status(), 200);
    await page.reload(); await page.getByRole("combobox", { name: "Время дневного дайджеста", exact: true }).filter({ hasText: "09:15" }).waitFor();

  });
  if (process.env.SEO_PLATFORM_E2E_RECOVERED_CRAWL_JOB_ID) {
    const recoveredId = process.env.SEO_PLATFORM_E2E_RECOVERED_CRAWL_JOB_ID;
    const response = await adminApi.get(`/admin/api/operations/${recoveredId}`); assert.equal(response.status(), 200);
    const operation = (await response.json()).data; assert.equal(operation.status, "COMPLETED"); assert.equal(operation.type, "TECHNICAL_CRAWL");
    const adminPage = await browser.newPage({ storageState: staff.storageState, viewport: { width: 1600, height: 1000 } });
    await adminPage.goto(`${base}/admin?screen=operations&operation=${recoveredId}`);
    await adminPage.locator(".operation-drawer").waitFor();
    await adminPage.screenshot({ path: output + "/recovered-crawl-admin.png", animations: "disabled" });
    await adminPage.close();
  }
  assert.deepEqual(errors, []); assert.deepEqual(serverErrors, []);
  await writeFile(output + "/crawl-page-map-results.json", JSON.stringify({ processed: crawl.processedUrls, blocked: crawl.blockedUrls, realHttpRequests: site.events.length, workerReceipts: await worker.prisma.remoteWorkTask.count({ where: { operationId: crawl.id, nodeId: worker.nodeId, state: "COMPLETED" } }), browserErrors: errors, serverErrors }, null, 2), { mode: 0o600 });
});
