import { assertSidebarBoundary } from "./workspace-sidebar-geometry.mjs";
import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { chromium, request } from "playwright";

test("note files: custom format creation, spreadsheet editing, persisted reload, preview and revoked public access", { skip: process.env.SEO_PLATFORM_E2E_CONFIRM !== "CREATE_TEST_DATA", timeout: 300_000 }, async (t) => {
  const base = process.env.SEO_PLATFORM_PUBLIC_URL, output = process.env.SEO_PLATFORM_E2E_OUTPUT_DIR;
  assert.equal(base, "https://144.31.221.28:3000");
  const [user, , , foreign] = JSON.parse(await readFile(process.env.SEO_PLATFORM_SESSION_FIXTURES, "utf8"));
  const api = await request.newContext({ baseURL: base, storageState: user.storageState }), outsider = await request.newContext({ baseURL: base, storageState: foreign.storageState });
  const browser = await chromium.launch({ headless: true }); t.after(async () => { await browser.close(); await api.dispose(); await outsider.dispose(); });
  async function call(method, path, data) { const csrf = (await api.storageState()).cookies.find((cookie) => cookie.name === "seo_csrf")?.value; const response = await api.fetch("/app/api/" + path, { method, headers: { Origin: base, "X-CSRF-Token": csrf, "Idempotency-Key": randomUUID() }, ...(data ? { data } : {}) }); const body = await response.json(); assert.ok(response.ok(), `${path}: ${response.status()} ${body.error?.code ?? ""}`); return body.data; }
  const workspace = await call("POST", "workspaces", { name: "Файлы проекта", country: "RU", locale: "ru", timezone: "Europe/Moscow", billingCurrency: "RUB" });
  const project = await call("POST", `workspaces/${workspace.id}/projects`, { name: "Файловая рабочая область", domain: "example.com", locale: "ru", timezone: "Europe/Moscow" });
  const context = await browser.newContext({ storageState: await api.storageState(), viewport: { width: 1440, height: 1000 } });
  await context.addCookies([{ name: "seo_workspace", value: workspace.id, url: base }, { name: "seo_project", value: project.id, url: base }]);
  const page = await context.newPage(), errors = []; page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(`${base}/app/projects/${project.id}/notes`);
  const separator = page.getByRole("separator", { name: "Изменить ширину списка файлов", exact: true });
  await separator.press("ArrowRight"); assert.equal(await separator.getAttribute("aria-valuenow"), "260");
  await separator.press("ArrowLeft"); assert.equal(await separator.getAttribute("aria-valuenow"), "248");
  await assertSidebarBoundary(page.locator('[data-workspace-sidebar="left"]'));
  const filenames = [];
  for (const [format, extension, content] of [["MARKDOWN", "md", "# План\n\n- [x] Проверка"], ["TEXT", "txt", "  обычный текст\n"], ["CSV", "csv", undefined], ["TSV", "tsv", "A\tB\n1\t2"], ["JSON", "json", '{"данные":true}']]) {
    await page.getByRole("button", { name: "Новый файл", exact: true }).first().click();
    const modal = page.getByRole("dialog", { name: "Новый файл", exact: true }); await modal.getByRole("textbox", { name: "Имя файла", exact: true }).fill(`Файл ${format}`);
    await modal.getByRole("combobox", { name: "Формат файла", exact: true }).click(); await page.getByRole("option", { name: new RegExp(`^\\.${extension}(?:\\s|$)`, "u") }).click();
    const created = page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname.endsWith(`/projects/${project.id}/notes`));
    await modal.getByRole("button", { name: "Создать", exact: true }).click(); const saved = await created; assert.equal(saved.status(), 201);
    const note = (await saved.json()).data; assert.equal(note.format, format); filenames.push({ id: note.id, format });
    if (format === "CSV") {
      await page.getByRole("textbox", { name: "Ячейка A1", exact: true }).fill("Запрос"); await page.getByRole("textbox", { name: "Ячейка B1", exact: true }).fill("Позиция");
      await page.getByRole("textbox", { name: "Ячейка A2", exact: true }).fill("ключ, слово"); await page.getByRole("textbox", { name: "Ячейка B2", exact: true }).fill("001");
      await page.getByRole("button", { name: "Строка", exact: true }).click(); await page.getByRole("textbox", { name: "Ячейка A3", exact: true }).fill("Третья строка");
      await page.getByRole("button", { name: "Колонка", exact: true }).click(); await page.getByRole("textbox", { name: "Ячейка C1", exact: true }).fill("Группа");
      await page.getByRole("textbox", { name: "Ячейка C1", exact: true }).press("ArrowDown");
      assert.equal(await page.getByRole("textbox", { name: "Ячейка C2", exact: true }).evaluate((element) => element === document.activeElement), true);
      await page.getByRole("textbox", { name: "Ячейка C2", exact: true }).evaluate((element) => {
        const clipboardData = new DataTransfer(); clipboardData.setData("text/plain", "Группа 1\nГруппа 2");
        element.dispatchEvent(new ClipboardEvent("paste", { clipboardData, bubbles: true, cancelable: true }));
      });
      await page.screenshot({ path: output + "/notes-csv-editor.png" });
    } else {
      if (format === "TSV") await page.getByRole("tab", { name: "Исходный текст", exact: true }).click();
      await page.getByRole("textbox", { name: "Содержимое файла", exact: true }).fill(content);
    }
    const updated = page.waitForResponse((response) => response.request().method() === "PATCH" && new URL(response.url()).pathname.endsWith(`/notes/${note.id}`));
    await page.getByRole("button", { name: "Сохранить", exact: true }).click(); assert.equal((await updated).status(), 200);
    const persisted = await call("GET", `projects/${project.id}/notes/${note.id}`); assert.equal(persisted.format, format);
    if (content !== undefined) assert.equal(persisted.markdown, content);
    else assert.equal(persisted.markdown, 'Запрос,Позиция,Группа\n"ключ, слово",001,Группа 1\nТретья строка,,Группа 2');
    const downloadStarted = page.waitForEvent("download"); await page.getByRole("button", { name: "Скачать", exact: true }).click();
    const download = await downloadStarted; assert.equal(download.suggestedFilename(), `Файл ${format}.${extension}`);
    assert.equal(await readFile(await download.path(), "utf8"), persisted.markdown);
    await page.getByRole("tab", { name: "Предпросмотр", exact: true }).click(); await page.screenshot({ path: output + `/notes-${extension}-preview.png` });
    await page.reload(); await page.getByRole("navigation", { name: "Навигация проекта", exact: true }).waitFor();
    await page.getByRole("button", { name: `Файл ${format}.${extension}`, exact: true }).click();
  }
  await context.grantPermissions(["clipboard-read", "clipboard-write"], { origin: base });
  await page.getByRole("button", { name: "Файл CSV.csv", exact: true }).click();
  const grid = page.getByRole("grid", { name: "Таблица файла", exact: true });
  const cell = (name) => page.getByRole("textbox", { name: "Ячейка " + name, exact: true });
  const column = (name) => page.getByRole("button", { name: "Выделить колонку " + name, exact: true });
  const row = (index) => page.getByRole("button", { name: "Выделить строку " + index, exact: true });
  const pasteFromClipboard = async (text) => { await page.evaluate(text => navigator.clipboard.writeText(text), text); await grid.press("Control+V"); };
  const undo = async () => { await grid.press("Control+Z"); };
  const menu = () => page.getByRole("menu", { name: "Действия с выделением", exact: true });
  await column("B").click({ button: "right" });
  await menu().getByRole("menuitem", { name: "Очистить содержимое", exact: true }).click();
  assert.equal(await cell("B2").inputValue(), ""); await undo(); assert.equal(await cell("B2").inputValue(), "001");
  await column("B").click({ button: "right" });
  await page.screenshot({ path: output + "/spreadsheet-column-menu.png", animations: "disabled" });
  await menu().getByRole("menuitem", { name: "Вставить колонки справа", exact: true }).click();
  assert.equal(await cell("D2").inputValue(), "Группа 1");
  await cell("D3").click(); await pasteFromClipboard('0009\t"две\nстроки"\tсумма\nx\ty\tz\n');
  assert.equal(await cell("D3").inputValue(), "0009"); assert.equal(await cell("E3").inputValue(), "две\nстроки"); assert.equal(await cell("F4").inputValue(), "z");
  await cell("D3").click(); await cell("F4").click({ modifiers: ["Shift"] }); await grid.press("Control+C");
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), '0009\t"две\nстроки"\tсумма\nx\ty\tz');
  await row(4).click(); await row(3).click({ modifiers: ["Shift"] }); await row(3).click({ button: "right" });
  await page.screenshot({ path: output + "/spreadsheet-row-menu.png", animations: "disabled" });
  await menu().getByRole("menuitem", { name: "Вставить строки выше", exact: true }).click();
  assert.equal(await cell("D5").inputValue(), "0009"); assert.equal(await cell("D6").inputValue(), "x"); await undo();
  await row(2).click({ button: "right" }); await menu().getByRole("menuitem", { name: "Удалить строки", exact: true }).click();
  assert.equal(await cell("D2").inputValue(), "0009"); await undo(); await grid.press("Control+Shift+Z");
  assert.equal(await cell("D2").inputValue(), "0009"); await undo();
  await column("C").click({ button: "right" }); await menu().getByRole("menuitem", { name: "Удалить колонки", exact: true }).click();
  assert.equal(await cell("C3").inputValue(), "0009"); await undo();
  await column("A").click(); await column("C").click({ modifiers: ["Control"] });
  assert.equal(await page.locator('[role="columnheader"][aria-selected="true"]').count(), 2);
  await cell("B2").click(); await cell("C3").click({ modifiers: ["Shift"] }); await pasteFromClipboard("900");
  assert.equal(await cell("B2").inputValue(), "900"); assert.equal(await cell("C3").inputValue(), "900"); await undo();
  assert.equal(await cell("B2").inputValue(), "001");
  await column("D").click({ button: "right" }); await menu().getByRole("menuitem", { name: "Копировать", exact: true }).focus();
  await page.keyboard.press("ArrowDown"); assert.equal(await menu().getByRole("menuitem", { name: "Вырезать", exact: true }).evaluate(element => element === document.activeElement), true);
  await page.keyboard.press("Escape");
  await page.evaluate(() => navigator.clipboard.writeText("замена"));
  await cell("A4").click({ button: "right" }); await menu().getByRole("menuitem", { name: "Вставить", exact: true }).click();
  await page.waitForFunction(() => document.querySelector('[data-cell="3:0"]')?.value === "замена");
  await cell("A4").click({ button: "right" }); await menu().getByRole("menuitem", { name: "Вырезать", exact: true }).click();
  await page.waitForFunction(() => document.querySelector('[data-cell="3:0"]')?.value === "");
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), "замена");
  await undo(); await undo();
  const resize = page.getByRole("separator", { name: "Ширина колонки B", exact: true });
  await resize.press("ArrowRight"); assert.equal(await resize.getAttribute("aria-valuenow"), "152");
  await cell("A4").dblclick(); await page.waitForFunction(() => document.activeElement?.getAttribute("data-cell") === "3:0");
  await page.keyboard.type("новый"); await page.keyboard.press("Alt+Enter"); await page.keyboard.type("текст");
  assert.equal(await cell("A4").inputValue(), "новый\nтекст"); await undo(); assert.equal(await cell("A4").inputValue(), "");
  const savedGrid = page.waitForResponse(response => response.request().method() === "PATCH" && new URL(response.url()).pathname.endsWith(`/notes/${filenames[2].id}`));
  await page.getByRole("button", { name: "Сохранить", exact: true }).click(); assert.equal((await savedGrid).status(), 200);
  const persistedGrid = await call("GET", `projects/${project.id}/notes/${filenames[2].id}`);
  assert.equal(persistedGrid.markdown, 'Запрос,Позиция,,Группа,,\n"ключ, слово",001,,Группа 1,,\nТретья строка,,,0009,"две\nстроки",сумма\n,,,x,y,z');
  await page.reload(); await page.getByRole("button", { name: "Файл CSV.csv", exact: true }).click(); assert.equal(await cell("E3").inputValue(), "две\nстроки");
  await page.screenshot({ path: output + "/spreadsheet-persisted.png", animations: "disabled" });
  await t.test("CSV separators at creation, editing, clipboard, reload, download and public preview", async () => {
    await page.getByRole("button", { name: "Новый файл", exact: true }).first().click();
    const modal = page.getByRole("dialog", { name: "Новый файл", exact: true });
    await modal.getByRole("textbox", { name: "Имя файла", exact: true }).fill("Разделители CSV");
    await modal.getByRole("combobox", { name: "Формат файла", exact: true }).click();
    await page.getByRole("option", { name: /^\.csv(?:\s|$)/u }).click();
    await modal.getByRole("combobox", { name: "Разделитель CSV", exact: true }).click();
    await page.getByRole("option", { name: "Точка с запятой (;)", exact: true }).click();
    const created = page.waitForResponse(response => response.request().method() === "POST" && new URL(response.url()).pathname.endsWith(`/projects/${project.id}/notes`));
    await modal.getByRole("button", { name: "Создать", exact: true }).click();
    const creation = await created; assert.equal(creation.status(), 201); const customNote = (await creation.json()).data;
    assert.equal(customNote.delimiter, ";"); assert.equal(customNote.markdown, ";\n;");
    await cell("A1").fill("A"); await cell("B1").fill("B");
    await cell("A2").fill("001,;"); await cell("B2").fill("two\nlines");
    await page.getByRole("combobox", { name: "Разделитель CSV", exact: true }).click();
    await page.getByRole("option", { name: "Свой символ", exact: true }).click();
    const symbol = page.getByRole("textbox", { name: "Свой разделитель", exact: true });
    await symbol.fill("ab"); assert.equal(await page.getByRole("button", { name: "Сохранить", exact: true }).isDisabled(), true);
    await symbol.fill("|"); assert.equal(await cell("A2").inputValue(), "001,;"); assert.equal(await cell("B2").inputValue(), "two\nlines");
    await cell("B2").click(); await pasteFromClipboard("0007\tnew\nvalue\tend");
    assert.equal(await cell("B2").inputValue(), "0007"); assert.equal(await cell("C3").inputValue(), "end");
    await symbol.fill("🧩"); assert.equal(await cell("A2").inputValue(), "001,;"); assert.equal(await cell("C3").inputValue(), "end");
    const saved = page.waitForResponse(response => response.request().method() === "PATCH" && new URL(response.url()).pathname.endsWith(`/notes/${customNote.id}`));
    await page.getByRole("button", { name: "Сохранить", exact: true }).click(); assert.equal((await saved).status(), 200);
    const stored = await call("GET", `projects/${project.id}/notes/${customNote.id}`); assert.equal(stored.delimiter, "🧩");
    assert.ok(stored.markdown.startsWith("A🧩B🧩"));
    await page.reload(); await page.getByRole("button", { name: "Разделители CSV.csv", exact: true }).click();
    assert.equal(await page.getByRole("textbox", { name: "Свой разделитель", exact: true }).inputValue(), "🧩");
    assert.equal(await cell("A2").inputValue(), "001,;"); assert.equal(await cell("C3").inputValue(), "end");
    const downloadStarted = page.waitForEvent("download"); await page.getByRole("button", { name: "Скачать", exact: true }).click();
    const download = await downloadStarted; assert.equal(await readFile(await download.path(), "utf8"), stored.markdown);
    await page.getByRole("tab", { name: "Предпросмотр", exact: true }).click();
    await page.screenshot({ path: output + "/notes-custom-separator.png", animations: "disabled" });
    await page.getByRole("combobox", { name: "Доступ к файлу", exact: true }).click(); await page.getByRole("option", { name: "Все по ссылке", exact: true }).click();
    const sharedResponse = page.waitForResponse(response => response.request().method() === "PATCH" && new URL(response.url()).pathname.endsWith(`/notes/${customNote.id}`));
    await page.getByRole("button", { name: "Сохранить", exact: true }).click(); assert.equal((await sharedResponse).status(), 200);
    const shared = await call("GET", `projects/${project.id}/notes/${customNote.id}`);
    const publicPage = await browser.newPage({ viewport: { width: 1200, height: 800 } });
    await publicPage.goto(`${base}/notes/${shared.publicToken}`);
    await publicPage.getByRole("grid", { name: "Таблица файла", exact: true }).waitFor();
    assert.ok((await publicPage.getByRole("grid").textContent()).includes("001,;"));
    assert.ok((await publicPage.getByRole("grid").textContent()).includes("end"));
    await publicPage.screenshot({ path: output + "/public-csv-custom-separator.png", animations: "disabled" }); await publicPage.close();
    // A delimiter-only public command must convert the existing file in the owner.
    const patch = await api.patch(`/app/api/projects/${project.id}/notes/${shared.id}`, { headers: { Origin: base, "X-CSRF-Token": (await api.storageState()).cookies.find(cookie => cookie.name === "seo_csrf").value, "If-Match": `"v${shared.version}"` }, data: { delimiter: "," } });
    assert.equal(patch.status(), 200); assert.equal((await patch.json()).data.delimiter, ",");
  });
  assert.ok([403,404].includes((await outsider.get(`/app/api/projects/${project.id}/notes`)).status()));
  assert.equal(await page.locator('select, input[type="date"], input[type="datetime-local"], input[type="time"]').count(), 0);
  await page.getByRole("button", { name: "Файл MARKDOWN.md", exact: true }).click();
  await page.getByRole("combobox", { name: "Доступ к файлу", exact: true }).click(); await page.getByRole("option", { name: "Все по ссылке", exact: true }).click(); const shareSaved = page.waitForResponse((response) => response.request().method() === "PATCH" && new URL(response.url()).pathname.endsWith(`/notes/${filenames[0].id}`)); await page.getByRole("button", { name: "Сохранить", exact: true }).click(); assert.equal((await shareSaved).status(), 200);
  const shared = await call("GET", `projects/${project.id}/notes/${filenames[0].id}`); assert.ok(shared.publicToken);
  const anonymous = await browser.newContext({ viewport: { width: 1440, height: 1000 } }), publicPage = await anonymous.newPage();
  await publicPage.goto(`${base}/notes/${shared.publicToken}`); await publicPage.getByRole("heading", { name: "Файл MARKDOWN.md", exact: true }).waitFor(); await publicPage.getByRole("heading", { name: "План", exact: true }).waitFor();
  await publicPage.screenshot({ path: output + "/public-note-desktop.png" }); await publicPage.setViewportSize({ width: 390, height: 844 }); assert.equal(await publicPage.evaluate(() => document.documentElement.scrollWidth > innerWidth), false); await publicPage.screenshot({ path: output + "/public-note-mobile.png" });
  await page.getByRole("combobox", { name: "Доступ к файлу", exact: true }).click(); await page.getByRole("option", { name: "Только участники", exact: true }).click(); const revoked = page.waitForResponse((response) => response.request().method() === "PATCH" && new URL(response.url()).pathname.endsWith(`/notes/${filenames[0].id}`)); await page.getByRole("button", { name: "Сохранить", exact: true }).click(); assert.equal((await revoked).status(), 200);
  await publicPage.reload(); await publicPage.getByRole("heading", { name: "Файл недоступен", exact: true }).waitFor();
  await anonymous.close();
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: output + "/notes-mobile.png" }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.getByRole("button", { name: "Файлы проекта", exact: true }).click(); await page.getByRole("button", { name: "Файл CSV.csv", exact: true }).click();
  await page.setViewportSize({ width: 320, height: 844 }); await page.getByRole("tab", { name: "Предпросмотр", exact: true }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: output + "/notes-csv-mobile.png" });
  assert.deepEqual(errors, []); await writeFile(output + "/note-files-results.json", JSON.stringify({ formats: filenames.map((note) => note.format), publicTokenRevoked: true, browserErrors: errors }, null, 2), { mode: 0o600 });
});
