import {
  processEnvironment,
  type ProcessDefinition
} from "@seo-platform/process-supervisor";

const CORE_KEYS = [
  "TELEGRAM_ALERTS_ENABLED",
  "OPERATIONAL_ALERTS_INTERNAL_URL",
  "OPERATIONAL_ALERT_TOKEN",
  "AUTH_ACCESS_COOKIE_NAME",
  "AUTH_ACCESS_TOKEN_TTL_MINUTES",
  "AUTH_COOKIE_SECURE",
  "AUTH_CSRF_COOKIE_NAME",
  "AUTH_DATA_ENCRYPTION_KEY",
  "AUTH_EMAIL_VERIFICATION_REQUIRED",
  "AUTH_EMAIL_VERIFICATION_TTL_MINUTES",
  "AUTH_EXPOSE_DEVELOPMENT_TOKENS",
  "AUTH_MFA_CHALLENGE_TTL_MINUTES",
  "AUTH_PASSWORD_PEPPER",
  "AUTH_PASSWORD_RESET_TTL_MINUTES",
  "AUTH_RECENT_AUTHENTICATION_MINUTES",
  "AUTH_SESSION_COOKIE_NAME",
  "AUTH_SESSION_TTL_DAYS",
  "AUTH_TOTP_ISSUER",
  "BILLING_RECONCILIATION_BATCH_SIZE",
  "BILLING_RECONCILIATION_ENABLED",
  "BILLING_RECONCILIATION_INTERVAL_MS",
  "BIND_ADDRESS",
  "CORS_ORIGINS",
  "INTERNAL_COMMAND_TIMEOUT_MS",
  "INTERNAL_REQUEST_TIMEOUT_MS",
  "JOBS_INTERNAL_URL",
  "JOBS_TO_PLATFORM_AUTH_EMAIL_TOKEN",
  "JOBS_TO_PLATFORM_AUTOMATION_TOKEN",
  "JOBS_TO_PLATFORM_BILLING_SETTLEMENT_TOKEN",
  "JOBS_TO_PLATFORM_RANK_GRANT_TOKEN",
  "JOBS_TO_SEO_DATA_TOKEN",
  "JOBS_TO_SEO_RANK_RESULT_TOKEN",
  "JOBS_TO_SEO_RANK_TOKEN",
  "NATS_AUTH_EMAIL_STREAM",
  "NATS_EVENT_ENVIRONMENT",
  "NATS_EVENT_STREAM",
  "NATS_URL",
  "OUTBOX_PUBLISH_ACK_TIMEOUT_MS",
  "OUTBOX_PUBLISH_BATCH_SIZE",
  "OUTBOX_PUBLISH_INTERVAL_MS",
  "OUTBOX_PUBLISH_MAX_ATTEMPTS",
  "OUTBOX_PUBLISH_RETRY_BASE_MS",
  "OUTBOX_PUBLISH_RETRY_MAX_MS",
  "OUTBOX_PUBLISHER_ENABLED",
  "PLATFORM_ARSENKIN_ENABLED",
  "PLATFORM_ARSENKIN_CLUSTERING_KEYWORD_LIMIT",
  "PLATFORM_ARSENKIN_DAILY_SPEND_LIMIT_MINOR",
  "PLATFORM_ARSENKIN_MONTHLY_SPEND_LIMIT_MINOR",
  "PLATFORM_ARSENKIN_RANK_KEYWORD_PRICE_MINOR",
  "PLATFORM_API_TO_JOBS_CREDENTIAL_TOKEN",
  "PLATFORM_API_TO_JOBS_TOKEN",
  "PLATFORM_API_TO_REALTIME_NOTIFICATION_TOKEN",
  "PLATFORM_API_TO_REALTIME_TOKEN",
  "PLATFORM_API_TO_SEO_DATA_TOKEN",
  "PLATFORM_DATABASE_POOL_MAX",
  "PLATFORM_DATABASE_URL",
  "PLATFORM_NATS_PASSWORD",
  "PLATFORM_NATS_USER",
  "PLATFORM_PORT",
  "PLATFORM_XMLSTOCK_ENABLED",
  "PLATFORM_XMLSTOCK_DAILY_SPEND_LIMIT_MINOR",
  "PLATFORM_XMLSTOCK_MONTHLY_SPEND_LIMIT_MINOR",
  "PLATFORM_XMLSTOCK_RANK_KEYWORD_PRICE_MINOR",
  "RANK_HISTORY_CURSOR_KEY",
  "REALTIME_INTERNAL_URL",
  "REALTIME_TO_PLATFORM_NOTIFICATION_TOKEN",
  "SEO_DATA_INTERNAL_URL",
  "SEO_DATABASE_POOL_MAX",
  "SEO_DATABASE_URL",
  "SEO_NATS_PASSWORD",
  "SEO_NATS_USER",
  "SEO_PORT",
  "SESSION_EXPIRY_SWEEPER_BATCH_SIZE",
  "SESSION_EXPIRY_SWEEPER_ENABLED",
  "SESSION_EXPIRY_SWEEPER_INTERVAL_MS",
  "SESSION_EXPIRY_SWEEPER_LOCK_TIMEOUT_MS",
  "SESSION_EXPIRY_SWEEPER_TRANSACTION_TIMEOUT_MS",
  "WEB_PUBLIC_URL",
  "TELEGRAM_LOGIN_ENABLED",
  "TELEGRAM_LOGIN_BOT_TOKEN",
  "TELEGRAM_LOGIN_BOT_USERNAME",
  "TELEGRAM_LOGIN_WEBHOOK_SECRET",
  "TELEGRAM_LOGIN_WEBHOOK_URL",
  "NPD_RECEIPTS_ENABLED",
  "NPD_PROCESSOR_API_TOKEN",
  "CRYPTO_PAY_ENABLED",
  "CRYPTO_PAY_API_TOKEN",
  "CRYPTO_PAY_API_BASE_URL",
  "CRYPTO_PAY_REQUEST_TIMEOUT_MS",
  "YOOKASSA_API_BASE_URL",
  "YOOKASSA_ENABLED",
  "YOOKASSA_REQUEST_TIMEOUT_MS",
  "YOOKASSA_RETURN_URL",
  "YOOKASSA_SECRET_KEY",
  "YOOKASSA_SHOP_ID",
  "YOOKASSA_VALIDATE_WEBHOOK_SOURCE_IP"
] as const;

const REALTIME_KEYS = [
  "BIND_ADDRESS",
  "NATS_EVENT_CONSUMER_DURABLE",
  "NATS_EVENT_CONSUMER_ENABLED",
  "NATS_EVENT_DLQ_STREAM",
  "NATS_EVENT_DLQ_SUBJECT",
  "NATS_EVENT_ENVIRONMENT",
  "NATS_EVENT_FETCH_EXPIRES_MS",
  "NATS_EVENT_MAX_ATTEMPTS",
  "NATS_EVENT_MAX_PAYLOAD_BYTES",
  "NATS_EVENT_PUBLISH_TIMEOUT_MS",
  "NATS_EVENT_RETRY_BASE_MS",
  "NATS_EVENT_RETRY_MAX_MS",
  "NATS_EVENT_SHUTDOWN_GRACE_MS",
  "NATS_EVENT_STREAM",
  "NATS_URL",
  "PLATFORM_API_TO_REALTIME_NOTIFICATION_TOKEN",
  "PLATFORM_API_TO_REALTIME_TOKEN",
  "WEB_ORIGINS",
  "WEB_PUSH_ACTIVE_FINGERPRINT_KEY_VERSION",
  "WEB_PUSH_ACTIVE_SUBSCRIPTION_KEY_VERSION",
  "WEB_PUSH_DELIVERY_AVAILABLE",
  "WEB_PUSH_ENDPOINT_ORIGINS",
  "WEB_PUSH_FINGERPRINT_KEYS",
  "WEB_PUSH_MAX_ACTIVE_DEVICES",
  "WEB_PUSH_REGISTRATION_ENABLED",
  "WEB_PUSH_SUBSCRIPTION_KEYS",
  "WEB_PUSH_VAPID_KEY_VERSION",
  "WEB_PUSH_VAPID_PUBLIC_KEY"
] as const;

const WEB_PUSH_KEYS = [
  "PLATFORM_API_INTERNAL_URL",
  "REALTIME_TO_PLATFORM_NOTIFICATION_TOKEN",
  "WEB_PUSH_ACTIVE_FINGERPRINT_KEY_VERSION",
  "WEB_PUSH_ACTIVE_SUBSCRIPTION_KEY_VERSION",
  "WEB_PUSH_DELIVERY_AUTHORIZATION_TIMEOUT_MS",
  "WEB_PUSH_DELIVERY_ENABLED",
  "WEB_PUSH_DELIVERY_LEASE_MS",
  "WEB_PUSH_DELIVERY_MAX_ATTEMPTS",
  "WEB_PUSH_DELIVERY_POLL_INTERVAL_MS",
  "WEB_PUSH_DELIVERY_RETRY_BASE_MS",
  "WEB_PUSH_DELIVERY_RETRY_MAX_MS",
  "WEB_PUSH_DELIVERY_SEND_TIMEOUT_MS",
  "WEB_PUSH_DELIVERY_TTL_SECONDS",
  "WEB_PUSH_EXPIRY_SWEEP_BATCH_SIZE",
  "WEB_PUSH_EXPIRY_SWEEP_INTERVAL_MS",
  "WEB_PUSH_FINGERPRINT_KEYS",
  "WEB_PUSH_SUBSCRIPTION_KEYS",
  "WEB_PUSH_VAPID_KEY_VERSION",
  "WEB_PUSH_VAPID_PRIVATE_KEY",
  "WEB_PUSH_VAPID_PUBLIC_KEY",
  "WEB_PUSH_VAPID_SUBJECT"
] as const;

const OPERATIONAL_ALERT_KEYS = [
  "OPERATIONAL_ALERT_TOKEN",
  "TELEGRAM_ALERT_BOT_TOKEN",
  "TELEGRAM_ALERT_CHAT_ID",
  "TELEGRAM_ALERT_ENVIRONMENT",
  "TELEGRAM_ALERT_THREAD_ID",
  "TELEGRAM_ALERTS_ENABLED"
] as const;

export function coreProcessDefinitions(
  env: NodeJS.ProcessEnv
): readonly ProcessDefinition[] {
  const definitions: ProcessDefinition[] = [
    {
      name: "alerts",
      moduleUrl: new URL("./alert.main.js", import.meta.url),
      environment: processEnvironment(env, OPERATIONAL_ALERT_KEYS, {
        BIND_ADDRESS: env.BIND_ADDRESS ?? "0.0.0.0",
        OPERATIONAL_ALERTS_PORT:
          env.OPERATIONAL_ALERTS_PORT ?? "4004"
      })
    },
    {
      name: "http",
      moduleUrl: new URL("./core.main.js", import.meta.url),
      environment: processEnvironment(env, CORE_KEYS)
    },
    {
      name: "realtime",
      moduleUrl: new URL("./realtime.main.js", import.meta.url),
      environment: processEnvironment(env, REALTIME_KEYS, {
        SERVICE_ROLE: "HTTP",
        DATABASE_URL: required(env, "REALTIME_DATABASE_URL"),
        DATABASE_POOL_MAX: env.REALTIME_DATABASE_POOL_MAX,
        REDIS_URL: required(env, "REALTIME_REDIS_URL"),
        NATS_USER: required(env, "REALTIME_NATS_USER"),
        NATS_PASSWORD: required(env, "REALTIME_NATS_PASSWORD"),
        PORT: env.REALTIME_PORT ?? "4003"
      })
    }
  ];

  if (env.WEB_PUSH_DELIVERY_ENABLED === "true") {
    definitions.push({
      name: "web-push",
      moduleUrl: new URL("./web-push-worker.main.js", import.meta.url),
      environment: processEnvironment(env, WEB_PUSH_KEYS, {
        SERVICE_ROLE: "WEB_PUSH_WORKER",
        DATABASE_URL: required(env, "WEB_PUSH_DATABASE_URL"),
        DATABASE_POOL_MAX: env.WEB_PUSH_DATABASE_POOL_MAX
      })
    });
  }
  if (env.NPD_RECEIPTS_ENABLED === "true") {
    definitions.push({
      name: "npd",
      moduleUrl: new URL("./npd-worker.main.js", import.meta.url),
      environment: processEnvironment(env, ["NPD_RECEIPTS_ENABLED", "NPD_PROCESSOR_API_TOKEN", "NPD_INN", "NPD_PASSWORD", "NPD_DEVICE_ID", "NPD_WORKER_READY_FILE", "PLATFORM_PORT"])
    });
  }
  return definitions;
}

function required(env: NodeJS.ProcessEnv, key: string): string {
  const value = env[key]?.trim();
  if (!value) throw new Error(`${key} is required by backend-core`);
  return value;
}
