bind 0.0.0.0
protected-mode yes
port 6379
daemonize no
supervised no
databases 1
aclfile /run/redis-runtime/users.acl
acl-pubsub-default resetchannels
enable-protected-configs no
enable-debug-command no
enable-module-command no
dir /data
save ""
appendonly no
maxmemory 256mb
maxmemory-policy allkeys-lru
maxclients 128
timeout 0
tcp-keepalive 300
latency-monitor-threshold 100
slowlog-log-slower-than 10000
slowlog-max-len 128
acllog-max-len 128
loglevel notice
logfile ""
