#!/bin/sh

set -eu

connector_user=jobs_connector
web_push_user=realtime_web_push
service_roles='platform_owner platform_runtime seo_owner seo_runtime jobs_owner jobs_runtime jobs_rank_runtime jobs_auth_email_runtime realtime_owner realtime_runtime'

if [ "${JOBS_CONNECTOR_DATABASE_USER:-$connector_user}" != "$connector_user" ]; then
  echo "JOBS_CONNECTOR_DATABASE_USER is immutable and must equal jobs_connector" >&2
  exit 1
fi

if [ "${POSTGRES_USER:-postgres}" = "$connector_user" ]; then
  echo "JOBS_CONNECTOR_DATABASE_USER must differ from POSTGRES_USER" >&2
  exit 1
fi

if [ "${REALTIME_WEB_PUSH_DATABASE_USER:-$web_push_user}" != "$web_push_user" ]; then
  echo "REALTIME_WEB_PUSH_DATABASE_USER is immutable and must equal realtime_web_push" >&2
  exit 1
fi

if [ "${POSTGRES_USER:-postgres}" = "$web_push_user" ]; then
  echo "REALTIME_WEB_PUSH_DATABASE_USER must differ from POSTGRES_USER" >&2
  exit 1
fi

for service_role in $service_roles; do
  if [ "${POSTGRES_USER:-postgres}" = "$service_role" ]; then
    echo "POSTGRES_USER must differ from canonical service database roles" >&2
    exit 1
  fi
done

write_hba() {
  echo "# Generated by infrastructure/postgres/config/start-postgres.sh"
  echo "# TYPE  DATABASE     USER                  ADDRESS  METHOD"
  echo 'local   platform_db  "platform_owner"                    scram-sha-256'
  echo 'local   platform_db  "platform_runtime"                  scram-sha-256'
  echo 'local   seo_db       "seo_owner"                         scram-sha-256'
  echo 'local   seo_db       "seo_runtime"                       scram-sha-256'
  echo 'local   jobs_db      "jobs_owner"                        scram-sha-256'
  echo 'local   jobs_db      "jobs_runtime"                      scram-sha-256'
  echo 'local   jobs_db      "jobs_rank_runtime"                 scram-sha-256'
  echo 'local   jobs_db      "jobs_auth_email_runtime"           scram-sha-256'
  echo 'local   realtime_db  "realtime_owner"                    scram-sha-256'
  echo 'local   realtime_db  "realtime_runtime"                  scram-sha-256'
  printf 'local   jobs_db      "%s"                         scram-sha-256\n' "$connector_user"
  printf 'local   realtime_db  "%s"                      scram-sha-256\n' "$web_push_user"
  echo 'local   replication  /^(platform|seo|jobs|realtime)_(owner|runtime)(_[a-z0-9_]+)?$  reject'
  echo 'local   all          /^(platform|seo|jobs|realtime)_(owner|runtime)(_[a-z0-9_]+)?$  reject'
  echo 'local   replication  /^jobs_rank_runtime(_[a-z0-9_]+)?$             reject'
  echo 'local   all          /^jobs_rank_runtime(_[a-z0-9_]+)?$             reject'
  echo 'local   replication  /^jobs_auth_email_runtime(_[a-z0-9_]+)?$       reject'
  echo 'local   all          /^jobs_auth_email_runtime(_[a-z0-9_]+)?$       reject'
  echo "local   replication  /^jobs_connector(_[a-z0-9_]+)?$             reject"
  echo "local   all          /^jobs_connector(_[a-z0-9_]+)?$             reject"
  echo "local   replication  /^realtime_web_push(_[a-z0-9_]+)?$          reject"
  echo "local   all          /^realtime_web_push(_[a-z0-9_]+)?$          reject"
  echo 'host    platform_db  "platform_owner"                    all      scram-sha-256'
  echo 'host    platform_db  "platform_runtime"                  all      scram-sha-256'
  echo 'host    seo_db       "seo_owner"                         all      scram-sha-256'
  echo 'host    seo_db       "seo_runtime"                       all      scram-sha-256'
  echo 'host    jobs_db      "jobs_owner"                        all      scram-sha-256'
  echo 'host    jobs_db      "jobs_runtime"                      all      scram-sha-256'
  echo 'host    jobs_db      "jobs_rank_runtime"                 all      scram-sha-256'
  echo 'host    jobs_db      "jobs_auth_email_runtime"           all      scram-sha-256'
  echo 'host    realtime_db  "realtime_owner"                    all      scram-sha-256'
  echo 'host    realtime_db  "realtime_runtime"                  all      scram-sha-256'
  printf 'host    jobs_db      "%s"                 all      scram-sha-256\n' "$connector_user"
  printf 'host    realtime_db  "%s"              all      scram-sha-256\n' "$web_push_user"
  echo 'host    replication  /^(platform|seo|jobs|realtime)_(owner|runtime)(_[a-z0-9_]+)?$  all      reject'
  echo 'host    all          /^(platform|seo|jobs|realtime)_(owner|runtime)(_[a-z0-9_]+)?$  all      reject'
  echo 'host    replication  /^jobs_rank_runtime(_[a-z0-9_]+)?$             all      reject'
  echo 'host    all          /^jobs_rank_runtime(_[a-z0-9_]+)?$             all      reject'
  echo 'host    replication  /^jobs_auth_email_runtime(_[a-z0-9_]+)?$       all      reject'
  echo 'host    all          /^jobs_auth_email_runtime(_[a-z0-9_]+)?$       all      reject'
  echo "host    replication  /^jobs_connector(_[a-z0-9_]+)?$     all      reject"
  echo "host    all          /^jobs_connector(_[a-z0-9_]+)?$     all      reject"
  echo "host    replication  /^realtime_web_push(_[a-z0-9_]+)?$  all      reject"
  echo "host    all          /^realtime_web_push(_[a-z0-9_]+)?$  all      reject"
  echo "local   all          all                           trust"
  echo "local   replication  all                           trust"
  echo "host    all          all                   all      scram-sha-256"
  echo "host    replication  all                   all      scram-sha-256"
}

if [ "${1:-}" = "--print-hba" ]; then
  write_hba
  exit 0
fi

: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}"
postgres_password_length=${#POSTGRES_PASSWORD}
if [ "$postgres_password_length" -lt 32 ] ||
  [ "$postgres_password_length" -gt 512 ]
then
  echo "POSTGRES_PASSWORD must contain 32..512 characters" >&2
  exit 1
fi
printable_postgres_password=$(
  printf '%s' "$POSTGRES_PASSWORD" | LC_ALL=C tr -d '[:cntrl:]'
)
if [ "$printable_postgres_password" != "$POSTGRES_PASSWORD" ]; then
  echo "POSTGRES_PASSWORD must not contain control characters" >&2
  exit 1
fi
lowercase_postgres_password=$(
  printf '%s' "$POSTGRES_PASSWORD" | tr '[:upper:]' '[:lower:]'
)
case $lowercase_postgres_password in
  replace-*|change-*|changeme*|example*|dummy-*|placeholder*|test-*|your-*|your_*)
    echo "POSTGRES_PASSWORD must not use an example placeholder" >&2
    exit 1
    ;;
esac
unset \
  postgres_password_length \
  printable_postgres_password \
  lowercase_postgres_password

hba_path=/tmp/seo-platform-pg_hba.conf
write_hba > "$hba_path"
chmod 0644 "$hba_path"

exec /usr/local/bin/docker-entrypoint.sh "$@"
