import type { Locale } from "./locales";

export { legalDocumentVersion } from "./legal-versions";
export const supportTelegram = "https://t.me/ker4ik13";
export const documentSlugs = ["terms", "privacy", "data-consent", "refunds", "cookies", "security", "help"] as const;
export type DocumentSlug = (typeof documentSlugs)[number];
export interface PublicDocument { title: string; description: string; legal: boolean; sections: readonly { title: string; paragraphs: readonly string[] }[] }
export function isDocumentSlug(value: string): value is DocumentSlug { return documentSlugs.some(slug => slug === value); }

const documents: Record<Locale, Record<DocumentSlug, PublicDocument>> = {
  ru: {
    terms: {
      title: "Условия использования и оплаты", description: "Доступ к SEOньорите, подписка, баланс данных и порядок работы с сервисом.", legal: true,
      sections: [
        { title: "1. Сервис и стороны", paragraphs: ["SEOньорита предоставляет доступ к программному сервису для SEO: работе с ключевыми запросами, поисковыми позициями, частотностью, страницами, заметками и совместными проектами. Исполнитель применяет налог на профессиональный доход в России. Его полные реквизиты указываются в разделе «Исполнитель» этой редакции до начала платных продаж.", "Создавая аккаунт и отдельно принимая эти условия, пользователь заключает договор на использование доступных функций. Заказывая платную подписку или данные, пользователь подтверждает состав, срок и цену, показанные перед оплатой. От лица организации действует уполномоченный представитель."] },
        { title: "2. Аккаунт и рабочая область", paragraphs: ["Укажите свой доступный email, подтвердите его и сохраняйте пароль, коды второго фактора и API-ключи в тайне. При подозрении на посторонний вход завершите неизвестные сессии и обратитесь в поддержку.", "Владелец рабочей области управляет командой, проектами, общим тарифом и балансом. Он определяет доступ участников и отвечает за выданные им полномочия. Права участника в отдельном проекте не расширяют его права в рабочей области.", "Пользователь сохраняет права на свои данные и разрешает их обработку в объёме, необходимом для выполнения выбранных операций. Не загружайте чужие секреты, незаконный контент или персональные данные без надлежащего основания. Не пытайтесь получить доступ к чужим проектам, нарушать работу сервиса или обходить ограничения провайдеров."] },
        { title: "3. Подписка и лимиты", paragraphs: ["Подписка определяет число проектов, участников, хранимых ключей, объём файлов, расписания и число одновременно выполняемых операций. Действующие цены и лимиты опубликованы на странице тарифов; точные условия заказа показываются в рабочей области перед оплатой.", "Бесплатный тариф доступен без банковской карты. В платную подписку не входит безлимитное получение внешних SEO-данных. Дополнительные запросы к провайдерам оплачиваются отдельно, если прямо не указано иное в выбранной версии тарифа.", "Подтверждённая оплата запускает оплаченный период. Досрочное продление того же тарифа сохраняет оставшиеся дни. При смене тарифа неиспользованная оплаченная стоимость переносится в дополнительные дни нового тарифа по его цене. Итоговый срок виден в настройках оплаты.", "Автоплатёж включается только после отдельного согласия на сохранение способа оплаты и автоматическое продление. Отключить продление можно в настройках оплаты. Уже оплаченный период сохраняется. При окончании доступа данные не удаляются автоматически: остаются просмотр и допустимый экспорт, новые операции могут быть ограничены."] },
        { title: "4. Баланс данных и внешние API", paragraphs: ["Баланс данных — аванс на операции внутри SEOньориты. Он не является банковским счётом, электронными деньгами, криптовалютой или средством расчётов с другими пользователями. Пополнение и расход отражаются в истории рабочей области.", "Перед платной операцией сервис показывает источник, охват и максимальную стоимость. После подтверждения сумма резервируется целиком либо по мере отправки отдельных частей съёма позиций. Цена съёма позиций фиксируется за ключ и выбранную глубину. Оплачиваются запросы, принятые провайдером; неиспользованный резерв освобождается. Отсутствие сайта в выдаче или нулевая частотность могут быть корректным платным результатом.", "Отмена останавливает новые обращения, но не отменяет уже отправленные провайдеру запросы. Если результат отправки неизвестен, спорная часть резерва остаётся на проверке: сервис не отправляет её повторно без разбирательства. Обратитесь в поддержку, если операция требует решения.", "При использовании собственного API-ключа расчёты идут по условиям вашего аккаунта провайдера; внутренний баланс не расходуется. Доступность, скорость, данные и ограничения внешних сервисов зависят также от провайдера. Вы разрешаете передачу выбранных ключевых фраз, домена и параметров только для заказанной операции."] },
        { title: "5. Платежи, документы и возвраты", paragraphs: ["Оплата производится только доступными на странице заказа способами. Данные банковской карты вводятся на стороне платёжного сервиса. Успешный возврат из платёжной формы сам по себе не означает оплату: доступ предоставляется после проверки платежа.", "Тестовые платежи не дают реального платного доступа и не пополняют баланс для внешних запросов. Для реального рублёвого расчёта исполнитель формирует чек НПД и передаёт его покупателю; автоматический способ выдачи не заменяет этой обязанности.", "Возврат рассматривается по заявке для неиспользованного оплаченного баланса и неиспользованной стоимости дней подписки. Подробности — на странице возвратов. Обязательные права покупателя, установленные применимым законодательством, сохраняются."] },
        { title: "6. Доступность и изменения", paragraphs: ["Сервис выполняет технические операции и предоставляет данные для анализа. Конкретная позиция в поиске, рост трафика, продажи и экономический результат не гарантируются. Пользователь самостоятельно проверяет выводы перед применением к своему сайту.", "При техническом сбое сервис сохраняет подтверждённые результаты и историю. Поддержка разбирает ошибки и спорные списания по идентификатору операции. Плановые работы и существенные изменения сообщаются доступными каналами; новая редакция условий не меняет цену уже оплаченного заказа задним числом.", "Существенные нарушения правил могут повлечь ограничение доступа с объяснением причины, кроме случаев, когда раскрытие запрещено законом или создаёт риск для других пользователей. Применимые императивные нормы об ответственности и защите потребителя имеют приоритет."] },
        { title: "7. Обращения", paragraphs: ["Поддержка доступна в Telegram @ker4ik13. Для вопроса об оплате укажите email аккаунта, рабочую область и номер платежа или заявки. Не отправляйте пароль, полный номер карты, резервные коды или API-ключи. Первичный ответ планируется в течение двух рабочих дней; срок решения зависит от сути обращения и применимых требований закона."] }
      ]
    },
    privacy: {
      title: "Политика конфиденциальности", description: "Какие данные использует SEOньорита, зачем они нужны и как управлять ими.", legal: true,
      sections: [
        { title: "1. Оператор и обращения", paragraphs: ["Оператором является исполнитель сервиса SEOньорита, применяющий НПД в России. Полные реквизиты указываются в разделе «Исполнитель» до публикации окончательной редакции. Контакт по вопросам данных: Telegram @ker4ik13."] },
        { title: "2. Данные и цели", paragraphs: ["Для регистрации и входа: email, отображаемое имя, подтверждение адреса, защищённое представление пароля, настройки языка и часового пояса. Для защиты аккаунта: сведения о сессиях, IP, типе браузера, втором факторе и событиях доступа. Пароль не хранится в открытом виде.", "Для работы команды: рабочие области, роли, приглашения, проекты, история изменений и предоставленные участниками материалы. Видимость данных внутри команды определяется владельцем и правами доступа. Публичная заметка доступна по ссылке только после явного включения такого режима.", "Для расчётов: сумма, назначение, время, статус и идентификаторы платежа, использованный тариф, остаток, расход и возвраты. Email для доставки документов, имя и ИНН покупателя-организации или ИП запрашиваются при необходимости. Полные реквизиты карты обрабатывает платёжный сервис.", "Для дополнительных функций: Telegram ID и сведения о привязке — при подключении входа через бота; параметры браузерной push-подписки — при её включении; API-ключи — при подключении собственных провайдеров. Эти возможности не включаются вместо пользователя."] },
        { title: "3. Основания и получатели", paragraphs: ["Данные обрабатываются для заключения и исполнения договора, выполнения установленных законом обязанностей, защиты сервиса и, в соответствующих случаях, на основании отдельного согласия. Рассылка рекламных материалов требует отдельного добровольного выбора; отказ не препятствует работе сервиса.", "Платёжный сервис получает необходимые сведения о заказе и покупателе. ФНС получает сведения для чеков НПД. SMTP-провайдер обрабатывает адрес и содержимое заказанного письма. При включённом входе через Telegram бот получает данные подтверждения.", "Выбранный SEO-провайдер получает только данные операции: например, поисковые фразы, домен, регион и настройки. Собственные ключи используются для вашего подключения. Платформа не продаёт пользовательские данные рекламодателям."] },
        { title: "4. Размещение и передача", paragraphs: ["Текущий сервер размещён в Германии. Для коммерческого запуска, направленного на граждан России, схема первичного сбора и хранения должна соответствовать требованиям локализации персональных данных. Эта редакция не подтверждает, что немецкий сервер сам по себе соответствует таким требованиям.", "До платного запуска оператор определяет и публикует фактическое размещение основных баз, сведения о привлечённых обработчиках и основания трансграничной передачи. При необходимости направляются отдельные уведомления Роскомнадзору. Согласие пользователя само по себе не отменяет обязательные требования локализации."] },
        { title: "5. Хранение, удаление и защита", paragraphs: ["Аккаунт и материалы проекта хранятся, пока нужны для предоставления сервиса. Окончание подписки не приводит к автоматическому удалению проектов. Технические временные данные имеют отдельные ограниченные сроки; срок тяжёлых результатов указан в тарифе. Финансовые и обязательные учётные документы сохраняются в течение требуемых законом сроков.", "При прекращении цели обработки данные удаляются или обезличиваются, если нет другого законного основания хранения. Заявки на исправление, выгрузку и удаление рассматривает оператор после соразмерной проверки принадлежности аккаунта; сохраняемые по закону записи отделяются от обычного использования сервиса.", "Применяются HTTPS, разграничение доступа рабочих областей, шифрование сохранённых API-ключей и платёжных контактных данных, журналирование значимых действий и резервное копирование. Не размещайте секреты в названиях, заметках или общедоступных ссылках."] },
        { title: "6. Ваши права", paragraphs: ["Можно запросить сведения об обработке, исправление неточных данных, ограничение или прекращение обработки при наличии оснований, выгрузку своих данных и отзыв согласия. Часть данных доступна для экспорта непосредственно в проекте. Отзыв согласия не отменяет обработку, необходимую для исполнения закона или иных сохраняющихся законных оснований.", "Обратитесь через аккаунт или Telegram @ker4ik13. Оператор сообщит о необходимых действиях и сроках. При разногласиях вы можете обратиться в уполномоченный орган или суд. Существенные изменения политики публикуются с датой редакции."] }
      ]
    },
    "data-consent": {
      title: "Согласие на обработку данных", description: "Отдельное согласие пользователя SEOньориты.", legal: true,
      sections: [
        { title: "Ваш выбор", paragraphs: ["Отмечая отдельное поле согласия, я свободно и осознанно разрешаю оператору SEOньориты, указанному в разделе «Исполнитель», обработку предоставленных мной данных для создания и обслуживания аккаунта, связи со мной по вопросам сервиса и работы выбранных функций.", "Состав данных: email, отображаемое имя, страна, язык, часовой пояс, настройки аккаунта, сведения о сессии и предоставленные при обращении контактные данные. При добровольном включении дополнительных возможностей — Telegram ID, параметры push-подписки и данные соответствующего подключения.", "Разрешённые действия: сбор, запись, систематизация, накопление, хранение, уточнение, использование, предоставление необходимым обработчикам для работы выбранной функции, блокирование, удаление и уничтожение, с автоматизацией и без неё. Сведения об обработчиках и размещении приведены в политике конфиденциальности.", "Согласие действует до достижения указанных целей или отзыва. Отозвать его можно через поддержку @ker4ik13. Оператор может продолжить обработку при наличии самостоятельного законного основания. Это согласие не включает рекламу, общедоступное распространение данных и не заменяет обязательные условия локализации."] }
      ]
    },
    refunds: {
      title: "Отмена подписки и возвраты", description: "Как отключить продление и вернуть неиспользованную оплаченную стоимость.", legal: true,
      sections: [
        { title: "Как подать заявку", paragraphs: ["В настройках «Тариф и оплата» откройте оплаченный заказ и выберите запрос возврата. Сервис покажет доступный неиспользованный остаток. Укажите сумму и причину. Если интерфейс недоступен, обратитесь в Telegram @ker4ik13 с номером заказа и email аккаунта.", "Подача заявки сама по себе не выполняет перевод и не останавливает работу. Решение принимает владелец сервиса. До одобрения доступный остаток может уменьшаться по мере использования; актуальная сумма проверяется при решении."] },
        { title: "Что можно вернуть", paragraphs: ["Неиспользованный оплаченный баланс данных — в пределах реально внесённых средств по соответствующему платежу, за вычетом проведённых и уже одобренных возвратов. Промо-баланс, бесплатные лимиты и тестовые платежи не обмениваются на деньги.", "Неиспользованную оплаченную стоимость подписки — пропорционально оставшейся части оплаченного периода с учётом предыдущих продлений, смен тарифа и возвратов. При одобрении соответствующая стоимость и длительность доступа уменьшаются, автоматическое продление отключается.", "Уже принятые провайдером платные запросы не считаются неиспользованным остатком. Спорные, ошибочные или дублированные списания проверяются отдельно. Обязательные права покупателя и случаи возврата, предусмотренные законом, не ограничиваются этой обычной политикой."] },
        { title: "После решения", paragraphs: ["При одобрении баланс резервируется либо пересчитываются оплаченные дни, чтобы эту стоимость нельзя было одновременно потратить и вернуть. Если платёжный сервис окончательно отклоняет возврат, удержанный остаток или стоимость дней восстанавливаются.", "Для рублёвых платежей возврат направляется через исходный платёжный сервис. Срок зачисления зависит от банка и способа оплаты. Статус виден в истории заявки; при необходимости исполнитель корректирует чек НПД.", "Отключение продления доступно отдельно от возврата и сохраняет уже оплаченный период. Удаление приложения, закрытие вкладки или выход из аккаунта не заменяют отключение автоплатежа."] }
      ]
    },
    cookies: {
      title: "Cookies и настройки браузера", description: "Сессии, выбор рабочей области и необходимые настройки интерфейса.", legal: false,
      sections: [
        { title: "Необходимые данные", paragraphs: ["Cookies используются для защищённого входа, защиты запросов, выбора рабочей области, проекта, языка и вида интерфейса. Чувствительная сессия недоступна JavaScript. Эти данные нужны для работы выбранных функций.", "Локальное хранилище браузера может сохранять настройки таблицы и незавершённый процесс загрузки. Не передавайте браузерный профиль посторонним. На общем устройстве завершайте сессию после работы."] },
        { title: "Аналитика и управление", paragraphs: ["Яндекс Метрика и рекламные пиксели сейчас не подключены. Административная статистика строится по собственным записям сервиса. Подключение необязательной внешней аналитики потребует обновления информации и соответствующего выбора пользователя.", "Удалить cookies можно в настройках браузера; после этого потребуется войти и выбрать рабочую область снова. Push-уведомления управляются отдельно в настройках сервиса и разрешениях браузера."] }
      ]
    },
    security: {
      title: "Защита аккаунта и данных", description: "Практические меры безопасности и связь с поддержкой.", legal: false,
      sections: [
        { title: "Защитите вход", paragraphs: ["Используйте уникальный пароль от 12 символов и включите двухфакторную аутентификацию. Сохраните резервные коды отдельно. В настройках безопасности можно просмотреть и завершить сессии неизвестных устройств.", "Вход через Telegram доступен после явной привязки к подтверждённому аккаунту. Сравнивайте код на странице с кодом в боте и подтверждайте только собственную попытку входа."] },
        { title: "Ограничивайте доступ", paragraphs: ["Выдавайте участникам и API-ключам только нужные права и проекты. При уходе сотрудника отзовите доступ; при утечке ключа перевыпустите его. Сохранённый секрет интеграции не отображается повторно.", "Публикуя заметку по ссылке, считайте её доступной любому получателю этой ссылки. Режим можно отозвать. Не публикуйте там пароли, ключи и персональные данные."] },
        { title: "Сообщите о проблеме", paragraphs: ["Напишите @ker4ik13, указав маршрут, время, идентификатор операции и безопасное описание воспроизведения. Не присылайте чужие данные или реальные секреты. Не продолжайте проверку, если она затрагивает чужой аккаунт или мешает работе пользователей."] }
      ]
    },
    help: {
      title: "Начало работы", description: "Первый проект, импорт, сбор данных и управление подпиской.", legal: false,
      sections: [
        { title: "1. Создайте рабочую область и проект", paragraphs: ["Зарегистрируйтесь, подтвердите email и создайте рабочую область. Добавьте проект с доменом без пути. В настройках проекта укажите город и часовой пояс. Язык интерфейса переключается в меню аккаунта и не меняет язык ваших ключей."] },
        { title: "2. Добавьте семантику", paragraphs: ["В разделе семантики вставьте запросы по одному на строке или импортируйте CSV, TSV, XLSX либо проект Key Collector .kc4. Перед публикацией проверьте колонки, язык и поведение дублей. Папки помогают организовать работу; SEO-кластеры отражают поисковый интент.", "Корзина позволяет восстановить удалённые запросы. Окончательное удаление необратимо. До крупных преобразований сохраните экспорт; история покажет выполненные изменения."] },
        { title: "3. Выберите источник данных", paragraphs: ["Подключите и проверьте собственный ключ XMLStock, Arsenkin или Keys.so. Если системные источники настроены владельцем сервиса, можно использовать баланс данных без собственного ключа. Для каждой операции выбираются основной источник и доступные резервы.", "В окне позиций, частотности, ИИ-ответов или кластеризации выберите параметры и охват. Для системного источника проверьте расчёт и подтвердите максимальную стоимость. Изменение параметров требует нового расчёта. Не запускайте повторно операцию с неизвестным результатом отправки."] },
        { title: "4. Следите за результатами", paragraphs: ["Задачи работают в фоне; страницу можно закрыть. Прогресс и результаты находятся в разделе операций. Результат кластеризации сначала является черновиком: изменения папок и кластеров применяются только после проверки и подтверждения.", "Карта страниц объединяет URL, назначенные запросы и результаты технического обхода. Обход соблюдает robots.txt и скорость сайта. Регулярные проверки настраиваются в расписаниях."] },
        { title: "5. Тариф, баланс и поддержка", paragraphs: ["Подписка оплачивает возможности платформы, баланс данных — внешние запросы. Текущие остатки видны в боковой панели. В оплате доступны история, продление, отключение автоплатежа и заявки на возврат.", "Если что-то не получилось, сохраните код запроса или номер операции и напишите @ker4ik13. При ошибке сети дождитесь обновления статуса перед новым платным запуском."] }
      ]
    }
  },
  en: {
    terms: { title: "Terms of use and payment", description: "Using SEOnorita, subscriptions, data balance and payments.", legal: true, sections: [
      { title: "1. Service and parties", paragraphs: ["SEOnorita provides SEO software for keywords, rankings, search volumes, pages, notes and shared projects. The provider is registered for professional income tax (NPD) in Russia. Full provider details must appear under Provider before paid sales begin.", "By creating an account and separately accepting these terms, you enter an agreement for available software features. Before a paid order, review and confirm its scope, duration and price. Anyone acting for an organization must be authorized to do so."] },
      { title: "2. Account and workspace", paragraphs: ["Use an accessible email address, verify it and protect your password, recovery codes and API keys. End unrecognized sessions and contact support if you suspect unauthorized access.", "The workspace owner manages projects, members, the plan and shared balance. Project roles can narrow, but never expand, workspace permissions. You retain rights to your data and permit processing needed for the operations you request. Do not upload unlawful content, other people's secrets or personal data without a proper basis. Do not access other users' projects or bypass provider restrictions."] },
      { title: "3. Subscription and limits", paragraphs: ["Subscriptions define project, member, keyword, file storage, schedule and concurrent operation limits. Published plans describe current prices and capacity; the exact version is shown before payment. The free plan needs no bank card. Unlimited external SEO data is not included in paid subscriptions.", "A verified payment starts the paid period. Early renewal of the same plan preserves remaining days. Switching plans converts unused paid service value into additional days at the new plan's price. The resulting end date is shown in billing settings.", "Automatic renewal requires separate consent to save a payment method and renew automatically. You can disable renewal in billing settings while keeping the paid period. Expiry does not automatically delete projects: viewing and permitted exports remain available while new operations may be restricted."] },
      { title: "4. Data balance and external APIs", paragraphs: ["Data balance is an advance for operations within SEOnorita. It is not a bank account, electronic money, cryptocurrency or a means of payment between users.", "Before a paid operation, review the source, scope and maximum cost. The amount is reserved after confirmation. Requests accepted by the provider are charged; unused reservations are released. A missing ranking or zero search volume may be a valid paid result.", "Canceling stops new requests but does not cancel requests already sent. Uncertain submissions are held for review rather than submitted again automatically. With your own API key, your provider account is charged under its terms and the platform data balance is not used. Provider availability, speed, limits and data may vary. Only the selected operation's phrases, domain and settings are sent to that provider."] },
      { title: "5. Payments and refunds", paragraphs: ["Pay using methods currently available at checkout. Card details are entered with the payment provider. Returning from checkout does not prove payment; the service verifies it before granting paid access.", "Test payments do not fund real external requests or activate paid access. For actual RUB payments, the provider issues and delivers an NPD receipt. Disabling automatic receipt issuance does not remove this obligation.", "Refunds of unused paid data balance and unused subscription value are reviewed on request. See the refund policy. Mandatory buyer rights under applicable law remain in effect."] },
      { title: "6. Availability and changes", paragraphs: ["The service supplies technical tools and data for analysis. Specific rankings, traffic, sales or financial results are not guaranteed. Check conclusions before applying them to your website.", "Confirmed results and history are retained during technical incidents. Support investigates errors and disputed charges using operation identifiers. Material changes and planned maintenance are communicated through available channels. New terms do not retroactively change the price of an already paid order.", "Serious misuse can result in access restrictions, with an explanation unless disclosure is prohibited or would endanger other users. Mandatory liability and consumer protection rules prevail."] },
      { title: "7. Support", paragraphs: ["Contact @ker4ik13 on Telegram. For billing questions, include your account email, workspace and order or request number. Do not send passwords, full card numbers, recovery codes or API keys. We aim to acknowledge requests within two working days; resolution depends on the issue and applicable legal requirements."] }
    ] },
    privacy: { title: "Privacy policy", description: "What SEOnorita processes, why it is needed and how to manage your data.", legal: true, sections: [
      { title: "1. Controller", paragraphs: ["The controller is the SEOnorita service provider registered for NPD in Russia. Full details must appear under Provider in the final published version. Contact for data requests: @ker4ik13 on Telegram."] },
      { title: "2. Data and purposes", paragraphs: ["Account and sign-in data includes email, display name, email verification, a protected password representation, language and time zone. Security records include sessions, IP addresses, browser information, second-factor settings and access events. Passwords are not stored in plaintext.", "Workspace data includes roles, invitations, projects, submitted materials and change history. Team visibility follows access permissions. Notes become accessible by public link only after that mode is explicitly enabled.", "Billing records include amounts, descriptions, timestamps, payment identifiers and status, plans, balances, usage and refunds. A delivery email and, when needed, a business buyer's name and tax ID are collected for documents. Full card details are handled by the payment provider.", "Optional features use Telegram identifiers for linked bot sign-in, browser push subscription details when enabled, and API keys for connections you add."] },
      { title: "3. Grounds and recipients", paragraphs: ["Processing supports the agreement, legal obligations, service protection and, where appropriate, separate consent. Marketing requires a separate voluntary choice and is not required to use the service.", "Payment providers receive necessary order and buyer information. The Russian tax authority receives NPD receipt data. SMTP providers process delivery addresses and requested email content. The Telegram bot processes sign-in confirmation when enabled. Selected SEO providers receive the requested operation's phrases, domain and parameters. User data is not sold to advertisers."] },
      { title: "4. Hosting and transfers", paragraphs: ["The current server is in Germany. A commercial launch targeting Russian citizens requires a primary collection and storage arrangement that meets applicable localization rules. This draft does not establish that German hosting alone satisfies those requirements.", "Before paid launch, the controller identifies and publishes actual primary database locations, relevant processors and grounds for international transfers, and makes required regulatory notifications. Consent does not replace mandatory localization requirements."] },
      { title: "5. Retention and protection", paragraphs: ["Accounts and project materials are retained while needed to provide the service. Subscription expiry does not automatically delete projects. Technical temporary data has separate limited retention; heavy result retention follows the plan. Financial and legally required records are retained for the required periods.", "When processing purposes end, data is deleted or anonymized unless another lawful retention basis exists. The controller reviews correction, export and deletion requests after proportionate account verification. Legally retained records are separated from ordinary service use.", "Controls include HTTPS, workspace access boundaries, encryption of stored API keys and billing contact data, significant-action audit records and backups. Do not put secrets in project names, notes or public links."] },
      { title: "6. Your choices", paragraphs: ["You can request processing information, correction, restriction or termination where applicable, an export and withdrawal of consent. Some exports are available directly within projects. Withdrawal does not stop processing required by law or another continuing lawful basis.", "Contact support through your account or @ker4ik13. The controller will explain the necessary steps and timing. You may contact the relevant authority or court. Material policy changes are published with a version date."] }
    ] },
    "data-consent": { title: "Personal data consent", description: "A separate consent for SEOnorita users.", legal: true, sections: [
      { title: "Your choice", paragraphs: ["By selecting the separate consent checkbox, I freely and knowingly authorize the SEOnorita controller identified under Provider to process data I submit for account creation and service, service-related contact and features I choose.", "This covers email, display name, country, language, time zone, account settings, session information and contact details submitted in support requests. Optional features may use a Telegram identifier, push subscription details or connection data.", "Permitted actions include collection, recording, organization, accumulation, storage, correction, use, necessary disclosure to processors, restriction and deletion, with or without automation. Processors and hosting are described in the privacy policy.", "Consent lasts until its purposes are fulfilled or it is withdrawn through @ker4ik13. The controller may continue processing on an independent lawful basis. This consent does not include marketing or public disclosure and does not replace mandatory localization requirements."] }
    ] },
    refunds: { title: "Cancellation and refunds", description: "Disable renewal and request a refund of unused paid value.", legal: true, sections: [
      { title: "Submit a request", paragraphs: ["Open a paid order under Plan and payments, then request a refund. Review the available unused value and enter an amount and reason. If the interface is unavailable, contact @ker4ik13 with your order number and account email.", "Submitting a request does not transfer funds or stop usage. The service owner reviews it. The available amount may decline as you use the service before approval; it is checked again when the decision is made."] },
      { title: "Refundable value", paragraphs: ["Unused paid data balance is refundable within actual funds paid for the relevant payment, less completed or approved refunds. Promotional balance, free limits and test payments cannot be exchanged for money.", "Unused paid subscription value is calculated proportionally to the remaining paid period, including previous renewals, plan changes and refunds. Approval reduces the corresponding value and access duration and disables automatic renewal.", "Provider requests already accepted are not unused value. Disputed, erroneous or duplicate charges are reviewed separately. Mandatory buyer rights and statutory refund cases are not limited by this ordinary policy."] },
      { title: "After the decision", paragraphs: ["Approval reserves funds or recalculates paid days so the same value cannot be spent and refunded. If the payment provider definitively rejects the refund, the held balance or subscription value is restored.", "RUB refunds are sent through the original payment provider. Bank settlement timing varies. Request status is shown in history and the provider corrects the NPD receipt when required.", "Disabling renewal is separate from requesting a refund and preserves the paid period. Closing a tab, deleting the app or signing out does not disable automatic renewal."] }
    ] },
    cookies: { title: "Cookies and browser settings", description: "Sessions, workspace selection and necessary interface settings.", legal: false, sections: [
      { title: "Necessary storage", paragraphs: ["Cookies support secure sign-in, request protection, workspace and project selection, language and interface preferences. Sensitive session cookies are not readable by JavaScript. Browser storage can retain table settings and unfinished upload state. Sign out on shared devices."] },
      { title: "Analytics and controls", paragraphs: ["Yandex Metrica and advertising pixels are not connected. Administration statistics use the service's own records. Optional external analytics will require updated information and an appropriate user choice.", "Deleting cookies in browser settings requires signing in and selecting your workspace again. Push notifications are managed separately in the service and browser permissions."] }
    ] },
    security: { title: "Account and data security", description: "Practical account protection and reporting issues.", legal: false, sections: [
      { title: "Protect sign-in", paragraphs: ["Use a unique password of at least 12 characters and enable two-factor authentication. Save recovery codes separately. Review sessions and end those you do not recognize.", "Telegram sign-in requires explicit linking to a verified account. Compare the browser code with the bot message and confirm only your own sign-in request."] },
      { title: "Limit access", paragraphs: ["Grant members and API keys only the permissions and projects they need. Revoke departing members and rotate exposed keys. Integration secrets are not shown again after saving.", "Anyone who receives a public note link can read that note. You can revoke sharing. Do not publish passwords, keys or personal data there."] },
      { title: "Report an issue", paragraphs: ["Contact @ker4ik13 with the route, time, operation identifier and a safe reproduction description. Do not send other users' data or real secrets. Stop testing if it reaches another account or disrupts users."] }
    ] },
    help: { title: "Getting started", description: "Your first project, imports, data collection and subscription management.", legal: false, sections: [
      { title: "1. Create a workspace and project", paragraphs: ["Register, verify your email and create a workspace. Add a project domain without a path. Set the city and time zone in project settings. Switch interface language in the account menu; keyword languages remain unchanged."] },
      { title: "2. Add keywords", paragraphs: ["Paste one keyword per line or import CSV, TSV, XLSX or a Key Collector .kc4 project. Review columns, language and duplicate handling before publishing. Folders organize work; SEO clusters represent search intent.", "Trash lets you restore removed keywords. Permanent deletion cannot be undone. Export data before large changes and use history to review completed edits."] },
      { title: "3. Choose a data source", paragraphs: ["Add and validate your own XMLStock, Arsenkin or Keys.so key. If platform sources are configured, use data balance without your own key. Each operation has a primary source and supported fallbacks.", "Choose parameters and scope for rankings, search volumes, AI answers or clustering. For a platform source, review the estimate and confirm the maximum cost. Parameter changes require a new estimate. Do not resubmit an operation with an unknown submission outcome."] },
      { title: "4. Review results", paragraphs: ["Jobs run in the background, so you can close the page. Progress and results appear under Operations. Clustering first creates a draft; review and confirm it before changing folders and clusters.", "The page map combines URLs, assigned keywords and crawl results. Crawls respect robots.txt and site speed limits. Set up recurring checks with schedules."] },
      { title: "5. Billing and help", paragraphs: ["Subscriptions pay for platform capacity; data balance pays for external requests. Current limits appear in the sidebar. Billing includes history, renewal, automatic payment cancellation and refund requests.", "Save the request or operation identifier and contact @ker4ik13 if something goes wrong. After a network error, wait for status reconciliation before starting another paid run."] }
    ] }
  }
};
export function publicDocument(locale: Locale, slug: DocumentSlug): PublicDocument { return documents[locale][slug]; }
