Foreground yes
TCPSocket 3310
TCPAddr 127.0.0.1
DatabaseDirectory __CLAMAV_DATABASE_DIR__
PidFile __CLAMAV_PID_FILE__
LogTime yes
LogVerbose no
OfficialDatabaseOnly yes
MaxConnectionQueueLength 20
MaxThreads 4
ReadTimeout 120
CommandReadTimeout 30
SendBufTimeout 500
MaxScanTime 900000
MaxScanSize 200M
MaxFileSize 100M
StreamMaxLength 100M
Bytecode yes
