import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const preparationTokenName = "JOBS_TO_SEO_RANK_TOKEN";
const resultTokenName = "JOBS_TO_SEO_RANK_RESULT_TOKEN";
const cursorKeyName = "RANK_HISTORY_CURSOR_KEY";

function secretOccurrences(compose, secretName) {
  const lines = compose.split(/\r?\n/u);
  const occurrences = [];
  let insideServices = false;
  let currentService;

  for (const [lineIndex, line] of lines.entries()) {
    if (line === "services:") {
      insideServices = true;
      currentService = undefined;
      continue;
    }

    if (insideServices && /^\S/u.test(line)) {
      insideServices = false;
      currentService = undefined;
    }

    if (insideServices) {
      const serviceMatch = /^  ([a-z0-9][a-z0-9-]*):\s*$/u.exec(line);
      if (serviceMatch) {
        currentService = serviceMatch[1];
      }
    }

    if (line.includes(secretName)) {
      occurrences.push({
        line: line.trim(),
        lineNumber: lineIndex + 1,
        service: insideServices ? currentService : undefined
      });
    }
  }

  return occurrences;
}

function interpolationSource(assignment) {
  const match = /\$\{([A-Z][A-Z0-9_]*):\?/u.exec(assignment);
  assert.ok(match, `required interpolation is missing in: ${assignment}`);
  return match[1];
}

test("rank result token is a distinct credential passed only to seo-data", async () => {
  const composeUrl = new URL("../compose.dokploy.yml", import.meta.url);
  const compose = await readFile(composeUrl, "utf8");
  const preparationOccurrences = secretOccurrences(
    compose,
    preparationTokenName
  );
  const resultOccurrences = secretOccurrences(compose, resultTokenName);

  assert.deepEqual(
    resultOccurrences.map(({ service }) => service),
    ["seo-data"],
    `${resultTokenName} must not reach anchors, workers or migrations`
  );
  assert.deepEqual(
    resultOccurrences.map(({ line }) => line),
    [
      `${resultTokenName}: \${${resultTokenName}:?${resultTokenName} is required}`
    ]
  );

  const preparationInSeoData = preparationOccurrences.find(
    ({ service }) => service === "seo-data"
  );
  const resultInSeoData = resultOccurrences[0];
  assert.ok(preparationInSeoData);
  assert.ok(resultInSeoData);
  assert.equal(
    interpolationSource(resultInSeoData.line),
    resultTokenName
  );
  assert.equal(
    interpolationSource(preparationInSeoData.line),
    preparationTokenName
  );
  assert.notEqual(
    interpolationSource(resultInSeoData.line),
    interpolationSource(preparationInSeoData.line),
    "normalized-result writes must not reuse the rank-preparation credential"
  );
});

test("rank history cursor key is passed only to seo-data", async () => {
  const composeUrl = new URL("../compose.dokploy.yml", import.meta.url);
  const compose = await readFile(composeUrl, "utf8");
  const occurrences = secretOccurrences(compose, cursorKeyName);

  assert.deepEqual(
    occurrences.map(({ service }) => service),
    ["seo-data"],
    `${cursorKeyName} must not reach anchors, workers or migrations`
  );
  assert.deepEqual(
    occurrences.map(({ line }) => line),
    [
      `${cursorKeyName}: \${${cursorKeyName}:?${cursorKeyName} is required}`
    ]
  );
});

test("new dedicated SEO Data secrets are intentionally empty in root example", async () => {
  const exampleUrl = new URL("../../.env.example", import.meta.url);
  const lines = (await readFile(exampleUrl, "utf8")).split(/\r?\n/u);

  for (const secretName of [resultTokenName, cursorKeyName]) {
    assert.deepEqual(
      lines.filter((line) => line.startsWith(`${secretName}=`)),
      [`${secretName}=`],
      `${secretName} must be generated by the operator, not copied from Git`
    );
  }
});
